INSERT INTO airports VALUES ('LAX', 'Los Angeles International'),
('JFK', 'John F. Kennedy International'),
('MCO', 'Orlando International'),
('DFW', 'Dallas/Fort Worth International'),
('MIA', 'Miami International'),
('ATL', 'Hartsfield–Jackson Atlanta International'),
('SFO', 'San Francisco International'),
('LAS', 'Harry Reid International Airport'),
('ORD', 'O Hare International'),
('MEX', 'Mexico City International'),
('PHX', 'Phoenix Sky Harbor International'),
('DEN', 'Denver International'),
('EWR', 'Newark Liberty International'),
('BCN', 'Barcelona–El Prat'),
('TLV', 'Ben Gurion'),
('TIJ', 'Tijuana International'),
('MNL', 'Ninoy Aquino International'),
('BOS', 'Logan International'),
('LGW', 'Gatwick'),
('IAH', 'George Bush Intercontinental'),
('GDL', 'Guadalajara International'),
('FCO', 'Leonardo da Vinci–Fiumicino Airport'),
('SEA', 'Seattle–Tacoma International'),
('LGA', 'LaGuardia'),
('PHL', 'Philadelphia International'),
('CUN', 'Cancún International'),
('YYZ', 'Toronto Pearson International'),
('FLL', 'Fort Lauderdale–Hollywood International'),
('MSP', 'Minneapolis–Saint Paul International'),
('BWI', 'Baltimore–Washington International'),
('MAD', 'Adolfo Suárez Madrid–Barajas'),
('CDG', 'Charles de Gaulle Airport'),
('NRT', 'Narita International'),
('HNL', 'Daniel K. Inouye International'),
('TPA', 'Tampa International'),
('IST', 'Istanbul Airport'),
('SAN', 'San Diego International'),
('DTW', 'Detroit Metropolitan'),
('SAW', 'Sabiha Gökçen International'),
('LIS', 'Lisbon Portela'),
('SLC', 'Salt Lake City International'),
('SJU', 'Luis Muñoz Marín International'),
('MDW', 'Chicago Midway International'),
('ATH', 'Athens International'),
('JED', 'King Abdulaziz International'),
('CLT', 'Charlotte Douglas International'),
('ORY', 'Paris Orly'),
('LHR', 'Heathrow'),
('IAD', 'Washington Dulles International'),
('AMS', 'Amsterdam Airport Schiphol'),
('DXB', 'Dubai International'),
('BKK', 'Suvarnabhumi'),
('YYC', 'Calgary International'),
('BOG', 'El Dorado International'),
('PDX', 'Portland International'),
('CAI', 'Cairo International'),
('SIN', 'Singapore Changi'),
('BER', 'Berlin Brandenburg'),
('SMF', 'Sacramento International'),
('SAL', 'Monseñor Óscar Arnulfo Romero International'),
('KUL', 'Kuala Lumpur International'),
('ICN', 'Incheon International'),
('LIM', 'Jorge Chávez International'),
('CLE', 'Cleveland Hopkins International'),
('YVR', 'Vancouver International'),
('CPH', 'Airport Copenhagen'),
('RDU', 'Raleigh–Durham International'),
('MXP', 'Milan–Malpensa'),
('DMK', 'Don Mueang International'),
('DPS', 'Ngurah Rai International'),
('DEL', 'Indira Gandhi International'),
('ONT', 'Ontario International'),
('MDE', 'José María Córdova International'),
('RUH', 'King Khalid International'),
('LTN', 'Luton'),
('NLU', 'Felipe Ángeles International Airport'),
('BUD', 'Budapest Ferenc Liszt International'),
('PVR', 'Licenciado Gustavo Díaz Ordaz International'),
('BNA', 'Nashville International'),
('MSY', 'Louis Armstrong New Orleans International'),
('AUS', 'Austin–Bergstrom International'),
('SJO', 'Juan Santamaría International'),
('HND', 'Haneda'),
('CVG', 'Cincinnati/Northern Kentucky International'),
('CEB', 'Mactan–Cebu International'),
('MPH', 'Godofredo P. Ramos'),
('AMM', 'Queen Alia International'),
('VCE', 'Venice Marco Polo'),
('CCS', 'Simón Bolívar International'),
('WAW', 'Warsaw Chopin'),
('SGN', 'Tan Son Nhat International'),
('SAT', 'San Antonio International'),
('HKT', 'Phuket International'),
('NCE', 'Nice Côte d Azur International'),
('IND', 'Indianapolis International'),
('VIE', 'Vienna International Airport'),
('PRG', 'Václav Havel Airport Prague'),
('TIA', 'Tirana International Airport Nënë Tereza'),
('OTP', 'Henri Coandă International'),
('SJD', 'Los Cabos International'),
('LHE', 'Allama Iqbal International'),
('NAP', 'Naples International'),
('GUA', 'La Aurora International'),
('PNH', 'Phnom Penh International'),
('HKG', 'Hong Kong International'),
('PVG', 'Shanghai Pudong International'),
('ISB', 'Islamabad International Airport'),
('EZE', 'Ministro Pistarini International'),
('BEG', 'Belgrade Nikola Tesla'),
('BOM', 'Chhatrapati Shivaji International'),
('ARN', 'Stockholm Arlanda'),
('OAK', 'Oakland International'),
('KEF', 'Keflavík International'),
('SYD', 'Sydney'),
('CTG', 'Rafael Núñez International'),
('DAC', 'Shahjalal International'),
('AYT', 'Antalya'),
('FRA', 'Frankfurt International Airport'),
('AUH', 'Zayed International Airport'),
('KTM', 'Tribhuvan International'),
('HYD', 'Rajiv Gandhi International'),
('KIX', 'Kansai International'),
('DUB', 'Dublin'),
('GRU', 'São Paulo–Guarulhos International'),
('BEY', 'Beirut–Rafic Hariri International'),
('YUL', 'Montréal–Pierre Elliott Trudeau International'),
('TPE', 'Taiwan Taoyuan International'),
('OSL', 'Oslo Airport, Gardermoen'),
('CMN', 'Mohammed V International'),
('SWF', 'New York Stewart International Airport'),
('SCL', 'Comodoro Arturo Merino Benítez International'),
('OPO', 'Porto'),
('BDL', 'Bradley International'),
('LOS', 'Murtala Muhammed International'),
('HAN', 'Noi Bai International'),
('MAN', 'Manchester'),
('GVA', 'Geneva'),
('YEG', 'Edmonton International'),
('DOH', 'Hamad International'),
('SJC', 'San Jose International'),
('EDI', 'Edinburgh Airport'),
('CMB', 'Bandaranaike International'),
('BJX', 'Del Bajío International'),
('MED', 'Prince Mohammad bin Abdulaziz'),
('HEL', 'Helsinki'),
('ZRH', 'Zürich Airport'),
('NBO', 'Jomo Kenyatta International'),
('KHI', 'Jinnah International'),
('GIG', 'Rio de Janeiro–Galeão International'),
('SNA', 'John Wayne'),
('PIT', 'Pittsburgh International'),
('MTY', 'Monterrey International'),
('LCA', 'Larnaca International'),
('JTR', 'Santorini (Thira) National'),
('CJS', 'Ciudad Juárez International'),
('PTY', 'Tocumen International'),
('MLE', 'Velana International'),
('EBL', 'Erbil International'),
('CMH', 'John Glenn Columbus International'),
('CHS', 'Charleston International'),
('AGP', 'Málaga'),
('PMI', 'Palma de Mallorca'),
('MCT', 'Muscat International'),
('RSW', 'Southwest Florida International'),
('KWI', 'Kuwait International'),
('TBS', 'Tbilisi International'),
('MUC', 'Munich'),
('UIO', 'Mariscal Sucre International'),
('CLO', 'Alfonso Bonilla Aragón International'),
('RNO', 'Reno–Tahoe International'),
('MEL', 'Melbourne'),
('DMM', 'King Fahd International'),
('DAD', 'Da Nang International'),
('RAK', 'Marrakesh Menara'),
('CNX', 'Chiang Mai International'),
('MCI', 'Kansas City International'),
('FAT', 'Fresno Yosemite International'),
('STL', 'St. Louis Lambert International'),
('OAX', 'Oaxaca International'),
('SHJ', 'Sharjah International'),
('MZT', 'Mazatlán International'),
('CGK', 'Soekarno–Hatta International'),
('BRU', 'Brussels'),
('DUS', 'Düsseldorf International Airport'),
('CAN', 'Guangzhou Baiyun International'),
('SDQ', 'Las Américas International'),
('MLM', 'Morelia International'),
('PEK', 'Beijing Capital International'),
('MAA', 'Chennai International'),
('PUJ', 'Punta Cana International'),
('AEP', 'Aeroparque Jorge Newbery'),
('CUZ', 'Alejandro Velasco Astete International'),
('BLR', 'Bengaluru International'),
('STN', 'London Stansted'),
('ELP', 'El Paso International'),
('MLA', 'Malta International'),
('GYE', 'José Joaquín de Olmedo International'),
('EVN', 'Zvartnots International'),
('CTA', 'Catania–Fontanarossa'),
('ORF', 'Norfolk International'),
('MYR', 'Myrtle Beach International'),
('RMO', 'Chișinău International'),
('KBL', 'Hamid Karzai International'),
('RIC', 'Richmond International'),
('BGW', 'Baghdad International'),
('MEM', 'Memphis International'),
('JAX', 'Jacksonville International'),
('SPU', 'Split'),
('KRK', 'John Paul II International Airport Kraków–Balice'),
('TUN', 'Tunis–Carthage International'),
('HAM', 'Hamburg'),
('PVD', 'Rhode Island T. F. Green Int''l Airport'),
('GYD', 'Heydar Aliyev International'),
('OKA', 'Naha'),
('FLR', 'Florence'),
('SOF', 'Sofia'),
('ABV', 'Nnamdi Azikiwe International'),
('OKC', 'Will Rogers World'),
('CRK', 'Clark International'),
('SAP', 'Ramón Villeda Morales International'),
('BOI', 'Boise'),
('TAS', 'Tashkent International'),
('PMO', 'Falcone–Borsellino'),
('OMA', 'Eppley Airfield'),
('ESB', 'Esenboğa International'),
('YOW', 'Ottawa Macdonald–Cartier International'),
('SAI', 'Siem Reap–Angkor International Airport'),
('YTZ', 'Billy Bishop Toronto City'),
('ADB', 'Adnan Menderes'),
('IBZ', 'Ibiza'),
('DBV', 'Dubrovnik'),
('STT', 'Cyril E. King'),
('OGG', 'Kahului'),
('YWG', 'Winnipeg James Armstrong Richardson International'),
('COK', 'Cochin International'),
('SDF', 'Louisville International'),
('PPS', 'Puerto Princesa International'),
('SVQ', 'Seville'),
('DVO', 'Francisco Bangoy International'),
('MGA', 'Augusto C. Sandino International'),
('ALG', 'Houari Boumediene'),
('VVI', 'Viru Viru International'),
('RGN', 'Yangon International'),
('ENI', 'El Nido'),
('AKL', 'Auckland'),
('TAG', 'Bohol-Panglao International'),
('PRN', 'Pristina International'),
('JNB', 'O. R. Tambo International'),
('ALC', 'Alicante–Elche'),
('MKE', 'General Mitchell International'),
('KBV', 'Krabi'),
('HER', 'Heraklion International'),
('AMD', 'Sardar Vallabhbhai Patel International'),
('TYS', 'McGhee Tyson'),
('BNE', 'Brisbane'),
('VLC', 'Valencia'),
('SMR', 'Simón Bolívar International'),
('CNF', 'Tancredo Neves International'),
('BAH', 'Bahrain International'),
('LYS', 'Lyon–Saint-Exupéry'),
('LPB', 'El Alto International'),
('USU', 'Francisco B. Reyes'),
('FNC', 'Cristiano Ronaldo International'),
('IAO', 'Sayak'),
('BSL', 'EuroAirport Basel Mulhouse Freiburg'),
('SSH', 'Sharm el-Sheikh International'),
('PNS', 'Pensacola International'),
('FAO', 'Faro'),
('ACC', 'Kotoka International'),
('VNO', 'Vilnius'),
('GLA', 'Glasgow'),
('SFB', 'Orlando Sanford International'),
('JMK', 'Mykonos Island National'),
('HRG', 'Hurghada International'),
('AVL', 'Asheville Regional'),
('TAC', 'Daniel Z. Romualdez'),
('PEI', 'Matecaña International'),
('PXM', 'Puerto Escondido International'),
('ALA', 'Almaty International'),
('DCA', 'Ronald Reagan Washington National'),
('CGY', 'Laguindingan Airport'),
('KOA', 'Kona International'),
('BUR', 'Hollywood Burbank'),
('MVD', 'Carrasco International'),
('BGY', 'Milan Bergamo International Airport'),
('ILO', 'Iloilo International'),
('DSM', 'Des Moines International'),
('MBJ', 'Sangster International'),
('CPT', 'Cape Town International'),
('PER', 'Perth'),
('BUF', 'Buffalo Niagara International'),
('IKA', 'Tehran Imam Khomeini International'),
('CUC', 'Camilo Daza International'),
('TGD', 'Podgorica'),
('SPX', 'Sphinx International Airport'),
('USM', 'Samui'),
('POS', 'Piarco International'),
('RIX', 'Riga International'),
('GRR', 'Gerald R. Ford International'),
('VTE', 'Wattay International'),
('EYW', 'Key West International'),
('QRO', 'Querétaro International'),
('LIN', 'Linate'),
('CCJ', 'Calicut International'),
('ASR', 'Erkilet International'),
('OLB', 'Olbia Costa Smeralda'),
('BAQ', 'Ernesto Cortissoz International'),
('SKG', 'Thessaloniki International Airport Macedonia'),
('BSB', 'Brasília International'),
('TGZ', 'Tuxtla Gutiérrez International'),
('ACA', 'Acapulco International'),
('TLL', 'Tallinn'),
('CTS', 'New Chitose'),
('RTB', 'Juan Manuel Gálvez International'),
('BIO', 'Bilbao'),
('NAV', 'Nevşehir Kapadokya'),
('AUA', 'Queen Beatrix International'),
('STR', 'Stuttgart'),
('FOC', 'Fuzhou Changle International'),
('XNA', 'Northwest Arkansas Regional'),
('CRL', 'Brussels South Charleroi'),
('MID', 'Mérida International'),
('CAP', 'Cap-Haïtien International'),
('TFS', 'Tenerife–South'),
('MRS', 'Marseille Provence'),
('CUR', 'Curaçao International'),
('ADA', 'Adana Şakirpaşa'),
('CUL', 'Bachigualato Federal International'),
('CBB', 'Jorge Wilstermann International'),
('TLC', 'Toluca International'),
('BLB', 'Panamá Pacífico International Airport'),
('PBC', 'Puebla International'),
('ANC', 'Ted Stevens Anchorage International'),
('SYR', 'Syracuse Hancock International'),
('BHX', 'Birmingham'),
('HOU', 'William P. Hobby'),
('FUK', 'Fukuoka'),
('SKP', 'Skopje Alexander the Great'),
('PUS', 'Gimhae International'),
('PKX', 'Beijing Daxing International Airport'),
('BRI', 'Bari Karol Wojtyła'),
('YHZ', 'Halifax Stanfield International'),
('BJV', 'Milas–Bodrum'),
('CCU', 'Netaji Subhas Chandra Bose International'),
('ADD', 'Addis Ababa Bole International'),
('TRZ', 'Tiruchirappalli International'),
('LKO', 'Chaudhary Charan Singh International'),
('NAN', 'Nadi International'),
('MXL', 'Mexicali International'),
('PEN', 'Penang International'),
('CUU', 'Chihuahua International'),
('PIE', 'St. Pete–Clearwater International'),
('AGU', 'Aguascalientes International'),
('REC', 'Recife/Guararapes–Gilberto Freyre International'),
('HMO', 'General Ignacio Pesqueira García International'),
('TRV', 'Trivandrum International'),
('BVA', 'Beauvais–Tillé'),
('HBE', 'Borg El Arab'),
('EOH', 'Olaya Herrera'),
('BCD', 'Bacolod–Silay'),
('ABQ', 'Albuquerque International Sunport'),
('SJJ', 'Sarajevo International'),
('BOD', 'Bordeaux–Mérignac'),
('VER', 'Veracruz International'),
('CFU', 'Corfu International'),
('KUT', 'David the Builder Kutaisi International'),
('BGA', 'Palonegro International'),
('MDZ', 'Governor Francisco Gabrielli International'),
('LIH', 'Lihue'),
('NAS', 'Lynden Pindling International'),
('LPA', 'Gran Canaria'),
('LAP', 'La Paz International'),
('BGO', 'Bergen Airport, Flesland'),
('FRU', 'Manas International'),
('AZA', 'Phoenix–Mesa Gateway'),
('SZX', 'Shenzhen Bao an International'),
('NQZ', 'Nursultan Nazarbayev International Airport'),
('XPL', 'Coronel Enrique Soto Cano Air Base'),
('BLQ', 'Bologna Guglielmo Marconi'),
('ZNZ', 'Abeid Amani Karume International'),
('PWM', 'Portland International Jetport'),
('SRQ', 'Sarasota–Bradenton International'),
('CLJ', 'Cluj International'),
('YLW', 'Kelowna International'),
('BQN', 'Aguadilla Rafael Hernandez'),
('DSS', 'Blaise Diagne International Airport'),
('CGN', 'Cologne Bonn Airport'),
('ISP', 'Long Island MacArthur'),
('DLM', 'Dalaman'),
('ZAG', 'Zagreb'),
('HRE', 'Harare International'),
('FLN', 'Hercílio Luz International'),
('ATQ', 'Sri Guru Ram Dass Jee International'),
('SAV', 'Savannah/Hilton Head International'),
('PVU', 'Provo Municipal'),
('PBI', 'Palm Beach International'),
('IAS', 'Iași International'),
('TNG', 'Tangier Ibn Battouta'),
('PSA', 'Pisa International'),
('ITM', 'Itami'),
('EIS', 'Terrance B. Lettsome International'),
('GOT', 'Göteborg Landvetter'),
('CHQ', 'Chania International'),
('BRC', 'San Carlos de Bariloche'),
('BKI', 'Kota Kinabalu International'),
('FSD', 'Sioux Falls Regional'),
('ECN', 'Ercan International'),
('YXE', 'Saskatoon John G. Diefenbaker International'),
('MBA', 'Moi International'),
('UBN', 'Chinggis Khaan International Airport'),
('TUL', 'Tulsa International'),
('VGA', 'Vijayawada'),
('CWB', 'Afonso Pena International'),
('GUM', 'Antonio B. Won Pat International'),
('GDN', 'Gdańsk Lech Wałęsa'),
('TLS', 'Toulouse–Blagnac'),
('TIV', 'Tivat'),
('YQR', 'Regina International'),
('BRS', 'Bristol'),
('SCQ', 'Santiago de Compostela'),
('AGA', 'Agadir–Al Massira'),
('CAK', 'Akron–Canton'),
('ADZ', 'Gustavo Rojas Pinilla International'),
('RHO', 'Rhodes International'),
('CXR', 'Cam Ranh International'),
('TZX', 'Trabzon'),
('REX', 'General Lucio Blanco International'),
('JAI', 'Jaipur International'),
('HUX', 'Bahías de Huatulco International'),
('TQO', 'Tulum International Airport'),
('ASU', 'Silvio Pettirossi International'),
('LIR', 'Daniel Oduber Quirós International'),
('DAR', 'Julius Nyerere International'),
('YYJ', 'Victoria International'),
('TFU', 'Chengdu Tianfu International Airport'),
('SHA', 'Shanghai Hongqiao International'),
('PSO', 'Antonio Nariño'),
('TFN', 'Tenerife-North'),
('IGR', 'Cataratas del Iguazú International'),
('PBG', 'Plattsburgh International'),
('GEG', 'Spokane International'),
('PEW', 'Bacha Khan International'),
('COR', 'Ingeniero Aeronáutico Ambrosio L.V. Taravella International'),
('KTW', 'Katowice International'),
('EBB', 'Entebbe International'),
('TAP', 'Tapachula International'),
('NTE', 'Nantes Atlantique'),
('ZIH', 'Ixtapa-Zihuatanejo International'),
('PGD', 'Punta Gorda'),
('LGK', 'Langkawi International'),
('DRP', 'Bicol International Airport'),
('VCP', 'Viracopos International'),
('KIN', 'Norman Manley International'),
('SXM', 'Princess Juliana International'),
('KLO', 'Kalibo International'),
('LJU', 'Ljubljana Jože Pučnik'),
('ATW', 'Appleton International'),
('PPT', 'Fa a ā International'),
('CNS', 'Cairns'),
('VLN', 'Arturo Michelena International'),
('CJU', 'Jeju International'),
('BDA', 'L.F. Wade International'),
('AHB', 'Abha Regional'),
('SUB', 'Juanda International'),
('POA', 'Salgado Filho International'),
('SDU', 'Santos Dumont'),
('CGH', 'São Paulo–Congonhas'),
('KGL', 'Kigali International'),
('CUE', 'Mariscal Lamar International'),
('VIX', 'Eurico de Aguiar Salles'),
('PAC', 'Albrook Marcos A. Gelabert International'),
('YIA', 'Yogyakarta International Airport'),
('STX', 'Henry E. Rohlsen'),
('VPS', 'Destin–Fort Walton Beach'),
('TUU', 'Tabuk Regional'),
('MFR', 'Rogue Valley International–Medford'),
('FOR', 'Pinto Martins – Fortaleza International'),
('MAO', 'Eduardo Gomes International'),
('EIN', 'Eindhoven'),
('RBA', 'Rabat–Salé'),
('GOI', 'Goa International'),
('PHC', 'Port Harcourt International'),
('MSO', 'Missoula International'),
('SGF', 'Springfield-Branson National'),
('LOP', 'Lombok International'),
('ROC', 'Greater Rochester International'),
('DTM', 'Dortmund'),
('ORN', 'Oran Es Sénia'),
('AXM', 'El Edén International'),
('MUX', 'Multan International'),
('BJL', 'Banjul International'),
('BWN', 'Brunei International'),
('BGI', 'Grantley Adams International'),
('BFS', 'Belfast International'),
('ABE', 'Lehigh Valley International'),
('TTN', 'Trenton–Mercer'),
('BZN', 'Bozeman Yellowstone International'),
('XMN', 'Xiamen Gaoqi International'),
('DGO', 'Durango International'),
('PDL', 'João Paulo II'),
('FNT', 'Bishop International'),
('MFE', 'McAllen Miller International'),
('HAJ', 'Hannover'),
('GMP', 'Gimpo International'),
('BOC', 'Bocas del Toro Isla Colón International'),
('VNS', 'Lal Bahadur Shastri International'),
('KAN', 'Mallam Aminu Kano International'),
('TOS', 'Tromsø Airport, Langnes'),
('SSA', 'Deputado Luís Eduardo Magalhães International'),
('LUX', 'Luxembourg'),
('DUR', 'Durban International'),
('PSP', 'Palm Springs International'),
('DYU', 'Dushanbe International'),
('SHE', 'Shenyang Taoxian International'),
('GSP', 'Greenville–Spartanburg International'),
('SLL', 'Salalah'),
('APW', 'Faleolo International'),
('DGT', 'Sibulan'),
('CNN', 'Kannur International Airport'),
('NUE', 'Nuremberg'),
('BIS', 'Bismarck Municipal'),
('OOL', 'Gold Coast'),
('IXM', 'Madurai'),
('TAO', 'Qingdao Jiaodong International Airport'),
('SKT', 'Sialkot International'),
('STI', 'Cibao International'),
('MAH', 'Menorca'),
('DLA', 'Douala International'),
('BUS', 'Batumi International'),
('ENU', 'Akanu Ibiam International'),
('ACY', 'Atlantic City International'),
('PQC', 'Phu Quoc International Airport'),
('EUG', 'Eugene'),
('NGO', 'Chubu Centrair International'),
('CID', 'The Eastern Iowa'),
('ZCL', 'Zacatecas International'),
('LCY', 'London City'),
('KCH', 'Kuching International'),
('CGP', 'Shah Amanat International'),
('ROB', 'Roberts International'),
('FAR', 'Hector International'),
('KNO', 'Kualanamu International'),
('FTE', 'Comandante Armando Tola International'),
('VTZ', 'Visakhapatnam'),
('IQT', 'Coronel FAP Francisco Secada Vignetta International'),
('HGH', 'Hangzhou Xiaoshan International'),
('GZT', 'Oğuzeli'),
('LIT', 'Clinton National'),
('ABJ', 'Port Bouet'),
('PNQ', 'Pune'),
('LPL', 'Liverpool John Lennon'),
('GYN', 'Santa Genoveva'),
('BBI', 'Biju Patnaik International'),
('VSA', 'Villahermosa International'),
('PFO', 'Paphos International'),
('YYT', 'St. John''s International'),
('TRC', 'Torreón International'),
('TPQ', 'Tepic International'),
('CRW', 'Yeager'),
('CJB', 'Coimbatore International'),
('CAG', 'Cagliari Elmas'),
('SKD', 'Samarkand International'),
('ITO', 'Hilo International'),
('TLH', 'Tallahassee International'),
('MRU', 'Sir Seewoosagur Ramgoolam International'),
('LPQ', 'Luang Prabang International'),
('CEI', 'Chiang Rai International'),
('CHC', 'Christchurch International'),
('BEL', 'Val de Cans International'),
('SXR', 'Srinagar International'),
('MFM', 'Macau International'),
('YQB', 'Québec City Jean Lesage International'),
('BXU', 'Bancasi'),
('YXX', 'Abbotsford International'),
('MSN', 'Dane County Regional'),
('UDI', 'Uberlandia'),
('GES', 'General Santos International'),
('IPC', 'Mataveri International'),
('ADL', 'Adelaide'),
('GRX', 'Federico García Lorca'),
('BNI', 'Benin'),
('TRD', 'Trondheim Airport, Værnes'),
('PBM', 'Johan Adolf Pengel International'),
('MAR', 'La Chinita International'),
('MAM', 'Matamoros International'),
('LBJ', 'Komodo'),
('IGU', 'Foz do Iguaçu International'),
('BTV', 'Burlington International'),
('TGU', 'Toncontín International'),
('TBP', 'Cap. FAP Pedro Canga Rodríguez'),
('UET', 'Quetta International'),
('NKG', 'Nanjing Lukou International'),
('TUS', 'Tucson International'),
('ACE', 'Lanzarote'),
('FUE', 'Fuerteventura'),
('AQP', 'Rodríguez Ballón International'),
('TSR', 'Timișoara Traian Vuia International'),
('JRO', 'Kilimanjaro International'),
('FIH', 'N djili'),
('BIL', 'Billings Logan International'),
('IXE', 'Mangaluru'),
('GEO', 'Cheddi Jagan International'),
('UKA', 'Ukunda'),
('RAI', 'Nelson Mandela International'),
('ZTH', 'Zakynthos International'),
('SVG', 'Stavanger Airport, Sola'),
('UTH', 'Udon Thani International'),
('ANU', 'V. C. Bird International'),
('PAT', 'Jay Prakash Narayan International'),
('ASM', 'Asmara International'),
('POZ', 'Poznań–Ławica'),
('LAD', 'Quatro de Fevereiro'),
('NCL', 'Newcastle'),
('BLI', 'Bellingham International'),
('SRE', 'Alcantarí International Airport'),
('BZE', 'Philip S. W. Goldson International'),
('USH', 'Ushuaia – Malvinas Argentinas International'),
('GJT', 'Grand Junction Regional'),
('MHT', 'Manchester–Boston Regional'),
('BON', 'Flamingo International'),
('TAM', 'Tampico International'),
('PIA', 'General Wayne A. Downing Peoria International'),
('ZYL', 'Osmani International'),
('PSC', 'Tri-Cities'),
('KHH', 'Kaohsiung International'),
('DAV', 'Enrique Malek International'),
('MPL', 'Montpellier–Méditerranée'),
('JHB', 'Senai International'),
('SPN', 'Saipan International'),
('SNN', 'Shannon'),
('MDT', 'Harrisburg International'),
('AVV', 'Avalon'),
('KIS', 'Kisumu International'),
('ALB', 'Albany International'),
('SZG', 'Salzburg'),
('QOW', 'Sam Mbakwe'),
('VRN', 'Verona Villafranca'),
('ICT', 'Wichita Dwight D. Eisenhower National'),
('DPL', 'Dipolog'),
('BHD', 'George Best Belfast City'),
('ZQN', 'Queenstown'),
('TSF', 'Treviso'),
('FEZ', 'Fès–Saïs'),
('EFL', 'Kephalonia International'),
('GZP', 'Gazipaşa'),
('BIQ', 'Biarritz Pays Basque'),
('XIY', 'Xi an Xianyang International'),
('EAS', 'San Sebastián'),
('IXB', 'Bagdogra'),
('HSV', 'Huntsville International'),
('NKC', 'Nouakchott International'),
('LUN', 'Kenneth Kaunda International'),
('MYD', 'Malindi'),
('LEX', 'Blue Grass'),
('SCV', 'Suceava International'),
('KMG', 'Kunming Changshui International'),
('TRF', 'Sandefjord Airport, Torp'),
('HDY', 'Hat Yai International'),
('STV', 'Surat'),
('LYP', 'Faisalabad International'),
('WRO', 'Copernicus Airport Wrocław'),
('GAU', 'Lokpriya Gopinath Bordoloi International'),
('POM', 'Jacksons International'),
('PAP', 'Toussaint Louverture International'),
('CKG', 'Chongqing Jiangbei International'),
('BGR', 'Bangor International'),
('PAS', 'Paros National'),
('FRS', 'Mundo Maya International'),
('LAO', 'Laoag International'),
('CTM', 'Chetumal International'),
('VAN', 'Van Ferit Melen'),
('RAP', 'Rapid City Regional'),
('SLA', 'Martín Miguel de Güemes International'),
('OVD', 'Asturias'),
('URT', 'Surat Thani International'),
('RFD', 'Chicago Rockford International'),
('VAR', 'Varna'),
('KOS', 'Sihanoukville International'),
('PKR', 'Pokhara'),
('LXR', 'Luxor International'),
('TNA', 'Jinan Yaoqiang International'),
('DOM', 'Douglas–Charles'),
('SCK', 'Stockton Metropolitan'),
('PDS', 'Piedras Negras International'),
('MGQ', 'Aden Adde International'),
('LCE', 'Golosón International'),
('WLG', 'Wellington International'),
('FCA', 'Glacier Park International'),
('EAR', 'Kearney Regional'),
('ARK', 'Arusha'),
('CKY', 'Conakry International'),
('CIA', 'Ciampino–G. B. Pastine International'),
('SLP', 'San Luis Potosí International'),
('FAE', 'Vágar'),
('IXC', 'Chandigarh International'),
('CZM', 'Cozumel International'),
('HGA', 'Hargeisa'),
('MJI', 'Mitiga International'),
('FWA', 'Fort Wayne International'),
('ZAM', 'Zamboanga International'),
('MLO', 'Milos Island National'),
('WUH', 'Wuhan Tianhe International'),
('MTR', 'Los Garzones'),
('ELH', 'North Eleuthera'),
('CPX', 'Benjamín Rivera Noriega'),
('PIU', 'FAP Captain Guillermo Concha Iberico International'),
('MKK', 'Molokai'),
('TRU', 'FAP Captain Carlos Martínez de Pinillos International'),
('BSR', 'Basra International'),
('XRY', 'Jerez'),
('TRN', 'Turin'),
('SEN', 'London Southend'),
('PZU', 'Port Sudan New International'),
('FNA', 'Lungi International'),
('SUF', 'Lamezia Terme International'),
('BDQ', 'Vadodara'),
('RCH', 'Almirante Padilla'),
('DAM', 'Damascus International'),
('TRS', 'Trieste – Friuli Venezia Giulia'),
('GCM', 'Owen Roberts International'),
('NYO', 'Stockholm Skavsta'),
('AHO', 'Alghero-Fertilia'),
('NVA', 'Benito Salas'),
('HPN', 'Westchester County'),
('NAT', 'Greater Natal International Airport'),
('FMM', 'Memmingen'),
('TJA', 'Capitan Oriel Lea Plaza'),
('IDR', 'Devi Ahilya Bai Holkar'),
('INV', 'Inverness'),
('ALS', 'San Luis Valley Regional'),
('SOQ', 'Domine Eduard Osok'),
('FAI', 'Fairbanks International'),
('VFA', 'Victoria Falls International'),
('LLW', 'Lilongwe International'),
('SOU', 'Southampton'),
('PVK', 'Aktion National'),
('LCG', 'A Coruña'),
('IDA', 'Idaho Falls Regional'),
('HRB', 'Harbin Taiping International'),
('DWC', 'Al Maktoum International'),
('ELQ', 'Prince Nayef bin Abdulaziz Regional'),
('EAM', 'Najran Regional Airport'),
('HBA', 'Hobart International'),
('GVR', 'Governador Valadares'),
('WDH', 'Hosea Kutako International'),
('MEC', 'Eloy Alfaro International'),
('RXS', 'Roxas'),
('IOS', 'Ilhéus Jorge Amado'),
('LMM', 'Los Mochis International'),
('CNY', 'Canyonlands Field'),
('RZE', 'Rzeszów–Jasionka'),
('HHN', 'Frankfurt–Hahn'),
('BKO', 'Bamako–Sénou International'),
('BDS', 'Brindisi'),
('HIJ', 'Hiroshima'),
('AAL', 'Aalborg'),
('VUP', 'Alfonso López Pumarejo'),
('GSO', 'Piedmont Triad International'),
('EDL', 'Eldoret International'),
('CLQ', 'Colima'),
('IOM', 'Isle of Man'),
('HMB', 'Sohag International'),
('LDE', 'Tarbes–Lourdes–Pyrénées'),
('CIX', 'FAP Captain José Abelardo Quiñones Gonzáles International'),
('LTO', 'Loreto International'),
('JNX', 'Naxos Island National'),
('UYU', 'Uyuni'),
('SBN', 'South Bend International'),
('TUG', 'Tuguegarao'),
('SPI', 'Abraham Lincoln Capital'),
('PDG', 'Minangkabau International'),
('OUD', 'Angads'),
('MYY', 'Miri'),
('KMS', 'Kumasi'),
('SAG', 'Shirdi'),
('LCK', 'Rickenbacker International'),
('RMF', 'Marsa Alam International'),
('IXR', 'Birsa Munda'),
('GNV', 'Gainesville Regional'),
('DJE', 'Djerba–Zarzis International'),
('LFW', 'Lomé–Tokoin International'),
('GOA', 'Genoa Cristoforo Colombo'),
('SLZ', 'Marechal Cunha Machado International'),
('MPM', 'Maputo International'),
('GIZ', 'Jazan'),
('CGB', 'Marechal Rondon International'),
('CXB', 'Cox''s Bazar'),
('ABB', 'Asaba International'),
('NSI', 'Yaoundé Nsimalen International'),
('BTS', 'Bratislava Airport'),
('KGS', 'Kos Island International'),
('HAS', 'Ha il Regional'),
('VQS', 'Antonio Rivera Rodríguez'),
('AJA', 'Ajaccio Napoleon Bonaparte'),
('TNR', 'Ivato International'),
('DLI', 'Lien Khuong'),
('TBU', 'Fuaʻamotu International'),
('SVD', 'Argyle International Airport'),
('CGR', 'Campo Grande International'),
('DLC', 'Dalian Zhoushuizi International'),
('BLL', 'Billund'),
('TIR', 'Tirupati'),
('COO', 'Cadjehoun'),
('MCZ', 'Zumbi dos Palmares International'),
('NVT', 'Navegantes'),
('DHM', 'Dharamsala airport'),
('TSA', 'Taipei Songshan'),
('NOB', 'Nosara'),
('NQY', 'Cornwall Airport Newquay'),
('BOB', 'Bora Bora'),
('UBP', 'Ubon Ratchathani'),
('OZC', 'Labo'),
('SUG', 'Surigao'),
('FPO', 'Grand Bahama International'),
('YQM', 'Greater Moncton Roméo LeBlanc International'),
('KUN', 'Kaunas'),
('MOT', 'Minot International'),
('CGO', 'Zhengzhou Xinzheng International'),
('TIF', 'Ta if Regional'),
('NAG', 'Dr. Babasaheb Ambedkar International'),
('WNP', 'Naga'),
('HTY', 'Hatay'),
('USA', 'Concord Regional'),
('TSN', 'Tianjin Binhai International'),
('LET', 'Alfredo Vásquez Cobo International'),
('EVV', 'Evansville Regional'),
('ABZ', 'Aberdeen'),
('BHM', 'Birmingham-Shuttlesworth International'),
('DNZ', 'Denizli Çardak'),
('BPS', 'Porto Seguro'),
('YNT', 'Yantai Penglai'),
('RVN', 'Rovaniemi'),
('PUY', 'Pula'),
('SID', 'Amílcar Cabral International'),
('SIG', 'Fernando Luis Ribas Dominicci'),
('BOJ', 'Burgas'),
('OSS', 'Osh'),
('MDC', 'Sam Ratulangi International'),
('MHH', 'Marsh Harbour'),
('CZL', 'Mohamed Boudiaf International'),
('UPG', 'Sultan Hasanuddin International'),
('HSR', 'Rajkot International Airport'),
('GPS', 'Seymour'),
('MHD', 'Mashhad International'),
('PLQ', 'Palanga International'),
('SZF', 'Samsun-Çarşamba'),
('CEN', 'Ciudad Obregón International'),
('SLU', 'George F. L. Charles'),
('SDR', 'Santander'),
('CKB', 'North Central West Virginia'),
('TPP', 'Cad. FAP Guillermo del Castillo Paredes'),
('MJT', 'Mytilene International'),
('MIR', 'Monastir Habib Bourguiba International'),
('NJF', 'Al Najaf International'),
('AYQ', 'Ayers Rock'),
('PMW', 'Palmas'),
('CTU', 'Chengdu Shuangliu International'),
('JUJ', 'Gobernador Horacio Guzmán International'),
('WIL', 'Wilson'),
('PIR', 'Pierre Regional'),
('PEM', 'Padre Aldamiz International'),
('SYZ', 'Shiraz International'),
('DIL', 'Presidente Nicolau Lobato International'),
('OHD', 'Ohrid St. Paul the Apostle'),
('OWB', 'Owensboro–Daviess County Regional'),
('GND', 'Maurice Bishop International'),
('DBR', 'Darbhanga Airport'),
('KUM', 'Yakushima'),
('CJC', 'El Loa'),
('SCO', 'Aktau'),
('SBH', 'Gustaf III'),
('DAY', 'Dayton International'),
('PLS', 'Providenciales International'),
('YHM', 'John C. Munro Hamilton International'),
('IBA', 'Ibadan'),
('RTM', 'Rotterdam The Hague'),
('GPT', 'Gulfport–Biloxi International'),
('THE', 'Senador Petronio Portella'),
('FLA', 'Gustavo Artunduaga Paredes'),
('ISG', 'Ishigaki'),
('TVC', 'Cherry Capital'),
('KKC', 'Khon Kaen'),
('LBA', 'Leeds Bradford'),
('NKT', 'Şırnak'),
('KBR', 'Sultan Ismail Petra'),
('TAB', 'Arthur Napoleon Raymond Robinson International'),
('BRE', 'Bremen'),
('CEZ', 'Cortez Municipal'),
('CHA', 'Chattanooga Metropolitan'),
('JUB', 'Juba International'),
('BCM', 'George Enescu International'),
('UPN', 'Uruapan International'),
('HLP', 'Halim Perdanakusuma International'),
('JER', 'Jersey'),
('AVP', 'Wilkes-Barre/Scranton International'),
('JBQ', 'La Isabela International'),
('RDM', 'Roberts Field'),
('MZL', 'La Nubia'),
('PLZ', 'Port Elizabeth'),
('VGO', 'Vigo–Peinador'),
('MGF', 'Maringá Regional'),
('SPC', 'La Palma'),
('BIA', 'Bastia – Poretta'),
('RAR', 'Rarotonga International'),
('EWN', 'Coastal Carolina Regional'),
('HAK', 'Haikou Meilan International'),
('ADE', 'Aden International Airport'),
('MDL', 'Mandalay International'),
('NDR', 'Nador International'),
('BFV', 'Buriram'),
('HTI', 'Great Barrier Reef'),
('OGU', 'Ordu–Giresun'),
('SEZ', 'Seychelles International'),
('TWU', 'Tawau'),
('SXB', 'Strasbourg'),
('NGB', 'Ningbo Lishe International'),
('KOJ', 'Kagoshima'),
('SKB', 'Robert L. Bradshaw International'),
('GOX', 'Manohar International Airport'),
('MMY', 'Miyako'),
('RZV', 'Rize–Artvin Airport'),
('UTP', 'U-Tapao International'),
('TRI', 'Tri-Cities Regional'),
('AES', 'Ålesund Airport, Vigra'),
('NLD', 'Nuevo Laredo International'),
('GOP', 'Mahayogi Gorakhnath'),
('TOL', 'Toledo Express'),
('FBM', 'Lubumbashi International'),
('LRD', 'Laredo International'),
('LVI', 'Harry Mwanga Nkumbula International'),
('JAC', 'Jackson Hole'),
('PAH', 'Barkley Regional'),
('GNY', 'Sanliurfa'),
('PUQ', 'Presidente Carlos Ibáñez del Campo International'),
('RNN', 'Bornholm'),
('GRB', 'Green Bay–Austin Straubel International'),
('YXY', 'Erik Nielsen Whitehorse International'),
('MSJ', 'Misawa'),
('LIL', 'Lille'),
('YQQ', 'CFB Comox'),
('GBE', 'Sir Seretse Khama International'),
('WNZ', 'Wenzhou Longwan International'),
('DED', 'Dehradun'),
('ILR', 'Ilorin International'),
('BLA', 'General José Antonio Anzoátegui International'),
('TKG', 'Radin Inten II International'),
('VEL', 'Vernal Regional'),
('CSX', 'Changsha Huanghua International'),
('MSS', 'Massena International'),
('LGB', 'Long Beach'),
('KSC', 'Košice International'),
('EYP', 'El Alcaraván'),
('TYL', 'Capitán FAP Víctor Montes Arias International'),
('YIW', 'Yiwu'),
('PGA', 'Page Municipal'),
('CIT', 'Shymkent International'),
('TNO', 'Tamarindo'),
('ISU', 'Sulaimaniyah International'),
('MRY', 'Monterey Regional'),
('IAG', 'Niagara Falls International'),
('MLH', 'Mulhouse/Basel EuroAirport French FR'),
('CVN', 'Clovis Municipal'),
('CGQ', 'Changchun Longjia International'),
('FEN', 'Fernando De Noronha'),
('SDK', 'Sandakan'),
('YQU', 'Grande Prairie'),
('SHV', 'Shreveport Regional'),
('YKA', 'Kamloops'),
('JPA', 'Presidente Castro Pinto International'),
('AKR', 'Akure'),
('ZAD', 'Zadar'),
('TUC', 'Teniente General Benjamín Matienzo International'),
('ORK', 'Cork'),
('BWA', 'Gautam Buddha'),
('BRM', 'Jacinto Lara International'),
('PBH', 'Paro'),
('ASW', 'Aswan International'),
('LEI', 'Almería'),
('HBX', 'Hubli'),
('MLB', 'Orlando Melbourne International'),
('VRC', 'Virac'),
('LDB', 'Londrina'),
('DIY', 'Diyarbakır'),
('IXJ', 'Jammu'),
('XQP', 'Quepos La Managua'),
('IXL', 'Kushok Bakula Rimpochee'),
('YXT', 'Northwest Regional Airport Terrace-Kitimat'),
('BUQ', 'Joshua Mqabuko Nkomo International'),
('RAO', 'Leite Lopes'),
('TBN', 'Waynesville-St. Robert Regional'),
('ASB', 'Ashgabat International'),
('CWL', 'Cardiff'),
('CYZ', 'Cauayan'),
('SYX', 'Sanya Phoenix International'),
('TSV', 'Townsville'),
('NDJ', 'N Djamena International'),
('PKZ', 'Pakse International'),
('PKU', 'Sultan Syarif Kasim II International'),
('KDU', 'Skardu'),
('HUI', 'Phu Bai International'),
('BOO', 'Bodø'),
('IPI', 'San Luis'),
('JIB', 'Djibouti–Ambouli International'),
('BDP', 'Bhadrapur'),
('LEJ', 'Leipzig/Halle Airport'),
('SJP', 'São José do Rio Preto'),
('MDQ', 'Astor Piazzolla International'),
('YQT', 'Thunder Bay International'),
('MZR', 'Mazar-i-Sharif International'),
('JKH', 'Chios Island National'),
('YCD', 'Nanaimo'),
('DRW', 'Darwin International'),
('OGS', 'Ogdensburg International'),
('MLI', 'Quad City International'),
('PNK', 'Supadio International'),
('AOR', 'Sultan Abdul Halim'),
('URA', 'Oral Ak Zhol'),
('ANR', 'Antwerp International'),
('UKB', 'Kobe'),
('LEB', 'Lebanon Municipal'),
('VLI', 'Bauerfield International'),
('BGF', 'Bangui M Poko International'),
('PPG', 'Pago Pago International'),
('LNS', 'Lancaster'),
('ATY', 'Watertown Regional'),
('UIH', 'Phu Cat'),
('GOH', 'Nuuk'),
('NBE', 'Enfidha–Hammamet International'),
('TER', 'Lajes Field'),
('LYR', 'Svalbard Airport, Longyear'),
('YYG', 'Charlottetown'),
('HKD', 'Hakodate'),
('BPN', 'Sultan Aji Muhammad Sulaiman'),
('JOI', 'Joinville-Lauro Carneiro de Loyola'),
('YKF', 'Region of Waterloo International'),
('NRR', 'José Aponte de la Torre'),
('VVC', 'La Vanguardia'),
('VIL', 'Dakhla'),
('IBE', 'Perales'),
('SCY', 'San Cristóbal'),
('AJU', 'Santa Maria'),
('KJT', 'Kertajati International'),
('BTJ', 'Sultan Iskandar Muda International'),
('IPL', 'Imperial County'),
('BJM', 'Bujumbura International'),
('LWB', 'Greenbrier Valley'),
('URC', 'Ürümqi Diwopu International'),
('GUW', 'Atyrau'),
('DAL', 'Dallas Love Field'),
('TIP', 'Tripoli International'),
('MTT', 'Minatitlán/Coatzacoalcos International'),
('TUP', 'Tupelo Regional'),
('LIO', 'Limón International'),
('CGI', 'Cape Girardeau Regional'),
('IRK', 'Kirksville Regional'),
('ROA', 'Roanoke–Blacksburg Regional'),
('MKG', 'Muskegon County'),
('KWL', 'Guilin Liangjiang International'),
('VRB', 'Vero Beach Regional'),
('LAU', 'Manda'),
('CAC', 'Cascavel'),
('SEU', 'Seronera Airstrip'),
('BVB', 'Boa Vista International'),
('PAE', 'Paine Field Everett'),
('APO', 'Antonio Roldán Betancourt'),
('BHB', 'Hancock County-Bar Harbor'),
('LNY', 'Lanai'),
('OUA', 'Ouagadougou'),
('YNB', 'Yanbu'),
('GHB', 'Governor''s Harbour'),
('ROR', 'Roman Tmetuchl International'),
('MOC', 'Montes Claros'),
('KLX', 'Kalamata International'),
('MMX', 'Malmö'),
('CBR', 'Canberra'),
('FLG', 'Flagstaff Pulliam'),
('PUU', 'Tres de Mayo'),
('SPD', 'Saidpur'),
('INN', 'Innsbruck'),
('VXE', 'Cesária Évora'),
('PPN', 'Guillermo León Valencia'),
('JDH', 'Jodhpur'),
('LMP', 'Lampedusa'),
('HOT', 'Memorial Field'),
('RKT', 'Ras Al Khaimah International'),
('SBD', 'San Bernardino International Airport'),
('TCQ', 'Coronel FAP Carlos Ciriani Santa Rosa International'),
('PTX', 'Pitalito'),
('PNA', 'Pamplona'),
('GGT', 'Exuma International'),
('HRL', 'Valley International'),
('FKB', 'Karlsruhe/Baden-Baden'),
('SPR', 'San Pedro'),
('TGM', 'Târgu Mureș International'),
('GCI', 'Guernsey'),
('BTH', 'Hang Nadim'),
('PCL', 'FAP Captain David Abensur Rengifo International'),
('SOW', 'Show Low Regional'),
('LBV', 'Libreville International'),
('ROS', 'Rosario – Islas Malvinas International'),
('JUL', 'Inca Manco Cápac International'),
('SBP', 'San Luis Obispo County Regional'),
('YQL', 'Lethbridge'),
('AUC', 'Santiago Pérez Quiroz'),
('AOI', 'Marche Airport'),
('SHD', 'Shenandoah Valley Regional'),
('PMC', 'El Tepual International'),
('HRO', 'Boone County'),
('QRW', 'Warri'),
('EAU', 'Chippewa Valley Regional'),
('FDF', 'Martinique Aimé Césaire International'),
('MCY', 'Sunshine Coast'),
('GWL', 'Gwalior'),
('KAD', 'Kaduna International'),
('BHO', 'Raja Bhoj'),
('TAE', 'Daegu International'),
('JAN', 'Jackson–Evers International'),
('NOU', 'La Tontouta International'),
('GRI', 'Central Nebraska Regional'),
('DEB', 'Debrecen International'),
('SBW', 'Sibu'),
('ORU', 'Juan Mendoza'),
('GTF', 'Great Falls International'),
('UDR', 'Maharana Pratap'),
('NGS', 'Nagasaki'),
('PAG', 'Pagadian'),
('CJJ', 'Cheongju International'),
('AMQ', 'Pattimura'),
('LJG', 'Lijiang Sanyi International'),
('GHV', 'Brașov-Ghimbav International Airport'),
('AOK', 'Karpathos Island National'),
('CBQ', 'Margaret Ekpo International'),
('GIB', 'Gibraltar International'),
('BIM', 'South Bimini'),
('ACK', 'Nantucket Memorial'),
('PHS', 'Phitsanulok'),
('KRS', 'Kristiansand Airport, Kjevik'),
('BLV', 'MidAmerica St. Louis'),
('PSM', 'Portsmouth International Airport at Pease'),
('MGW', 'Morgantown Municipal'),
('HHQ', 'Hua Hin'),
('POP', 'Gregorio Luperón International'),
('ZVK', 'Savannakhet'),
('FMO', 'Münster Osnabrück International'),
('YMM', 'Fort McMurray International'),
('RMU', 'Región de Murcia'),
('BMI', 'Central Illinois Regional'),
('BRL', 'Southeast Iowa Regional'),
('JSI', 'Skiathos Island National'),
('BKW', 'Raleigh County Memorial'),
('HET', 'Hohhot Baita International'),
('JHM', 'Kapalua'),
('YBL', 'Campbell River'),
('KYA', 'Konya'),
('EMA', 'East Midlands'),
('OUL', 'Oulu'),
('SDJ', 'Sendai'),
('IMP', 'Imperatriz'),
('PLM', 'Sultan Mahmud Badaruddin II International'),
('ERZ', 'Erzurum'),
('TBZ', 'Tabriz International'),
('GIL', 'Gilgit'),
('GAY', 'Gaya'),
('FSC', 'Figari–Sud Corse'),
('MCP', 'Macapá International'),
('MSL', 'Northwest Alabama Regional'),
('EVE', 'Harstad/Narvik Airport, Evenes'),
('TKU', 'Turku'),
('IWD', 'Gogebic–Iron County'),
('KWE', 'Guiyang Longdongbao International'),
('YZF', 'Yellowknife'),
('IXZ', 'Veer Savarkar International'),
('MWZ', 'Mwanza'),
('OMO', 'Mostar'),
('CBO', 'Awang'),
('PUB', 'Pueblo Memorial'),
('TDX', 'Trat'),
('KDH', 'Kandahar International'),
('IPH', 'Sultan Azlan Shah'),
('SRG', 'Ahmad Yani International'),
('IVL', 'Ivalo'),
('SFT', 'Skellefteå'),
('TCO', 'La Florida'),
('PPP', 'Whitsunday Coast'),
('CXH', 'Vancouver Harbour Flight Centre'),
('JNU', 'Juneau International'),
('CGM', 'Camiguin'),
('NIM', 'Diori Hamani International'),
('NNG', 'Nanning Wuxu International'),
('SBA', 'Santa Barbara Municipal'),
('BEW', 'Beira'),
('BZO', 'Bolzano Airport'),
('YXU', 'London International'),
('ULH', 'Prince Abdul Majeed bin Abdulaziz Domestic'),
('YFB', 'Iqaluit'),
('CJA', 'Mayor General FAP Armando Revoredo Iglesias'),
('RBQ', 'Rurrenabaque'),
('JLR', 'Jabalpur'),
('PNT', 'Teniente Julio Gallardo'),
('ACO', 'Cobano Airport'),
('YXS', 'Prince George'),
('HPH', 'Cat Bi International'),
('SBZ', 'Sibiu International'),
('MAF', 'Midland International Air and Space Port'),
('YFC', 'Fredericton International'),
('AIT', 'Aitutaki'),
('QUO', 'Akwa Ibom'),
('STM', 'Santarém-Maestro Wilson Fonseca'),
('YXJ', 'Fort St. John'),
('ECP', 'Northwest Florida Beaches International'),
('SMX', 'Santa Maria Public'),
('CCP', 'Carriel Sur International'),
('PTP', 'Pointe-à-Pitre International'),
('TZA', 'Belize City Municipal'),
('BNX', 'Banja Luka International'),
('HTS', 'Tri-State'),
('RMQ', 'Taichung'),
('STS', 'Charles M. Schulz–Sonoma County'),
('SHO', 'King Mswati III International'),
('MBL', 'Manistee County Blacker'),
('TST', 'Trang'),
('KKN', 'Kirkenes Airport, Høybuktmoen'),
('DOD', 'Dodoma'),
('UIN', 'Quincy Regional'),
('DUD', 'Dunedin'),
('BJA', 'Abane Ramdane'),
('NQN', 'Presidente Perón International'),
('BFD', 'Bradford Regional'),
('AUG', 'Augusta State'),
('TVF', 'Thief River Falls Regional'),
('TAK', 'Takamatsu'),
('AKX', 'Aktobe'),
('GOM', 'Goma International'),
('RPR', 'Swami Vivekananda'),
('VDO', 'Van Don International Airport'),
('MQM', 'Mardin'),
('MKL', 'McKellar–Sipes Regional'),
('PUW', 'Pullman–Moscow Regional'),
('BSO', 'Basco'),
('IPN', 'Usiminas'),
('MCK', 'McCook Ben Nelson Regional'),
('CEC', 'Del Norte County'),
('BAG', 'Loakan Airport'),
('KOE', 'El Tari International'),
('EJA', 'Yariguíes'),
('RNS', 'Rennes–Saint-Jacques'),
('HOF', 'Al-Ahsa International'),
('SVJ', 'Svolvær Airport, Helle'),
('AKJ', 'Asahikawa'),
('LLA', 'Luleå'),
('CAE', 'Columbia Metropolitan'),
('CAY', 'Cayenne – Félix Eboué'),
('LSC', 'La Florida'),
('HDS', 'Air Force Base Hoedspruit'),
('PDT', 'Eastern Oregon Regional'),
('PNZ', 'Petrolina'),
('IGD', 'Iğdır'),
('GFK', 'Grand Forks International'),
('NUM', 'Neom Bay Airport'),
('XKH', 'Xieng Khouang'),
('KHN', 'Nanchang Changbei International'),
('TEX', 'Telluride Regional'),
('CRA', 'Craiova International'),
('SLK', 'Adirondack Regional'),
('ELM', 'Elmira/Corning Regional'),
('SXV', 'Salem'),
('MAB', 'Marabá'),
('LBE', 'Arnold Palmer Regional'),
('TTU', 'Sania Ramel'),
('SVC', 'Grant County'),
('COS', 'Colorado Springs'),
('ARU', 'Araçatuba'),
('RUN', 'Roland Garros'),
('LBU', 'Labuan'),
('MZV', 'Mulu'),
('WUX', 'Sunan Shuofang International'),
('RJA', 'Rajahmundry'),
('UVF', 'Hewanorra International'),
('VDH', 'Dong Hoi'),
('PKB', 'Mid-Ohio Valley Regional'),
('PVH', 'Governador Jorge Teixeira de Oliveira International'),
('CFR', 'Caen – Carpiquet'),
('PSS', 'Libertador General José de San Martín'),
('KEP', 'Nepalgunj'),
('MAZ', 'Eugenio María de Hostos'),
('AOJ', 'Aomori'),
('ATZ', 'Assiut'),
('LST', 'Launceston'),
('LOE', 'Loei'),
('BTU', 'Bintulu'),
('SZB', 'Sultan Abdul Aziz Shah'),
('KIJ', 'Niigata'),
('TML', 'Tamale'),
('GRZ', 'Graz'),
('BMV', 'Buon Ma Thuot'),
('CIY', 'Comiso'),
('MQP', 'Kruger Mpumalanga International'),
('BKG', 'Branson'),
('NST', 'Nakhon Si Thammarat'),
('EDO', 'Balıkesir Koca Seyit'),
('KCZ', 'Kōchi'),
('ARI', 'Chacalluta International'),
('UIB', 'El Caraño'),
('TLN', 'Toulon–Hyères'),
('CIJ', 'Captain Aníbal Arab'),
('MLN', 'Melilla'),
('GNS', 'Binaka'),
('BES', 'Brest Bretagne'),
('NSN', 'Nelson'),
('BMA', 'Stockholm Bromma'),
('ABT', 'Al-Baha Domestic'),
('ELS', 'East London'),
('HSA', 'Turkistan International Airport'),
('JAU', 'Francisco Carle'),
('YGJ', 'Miho-Yonago'),
('ASP', 'Alice Springs'),
('SRP', 'Stord Airport, Sørstokken'),
('KNU', 'Kanpur'),
('YXH', 'Medicine Hat'),
('BIR', 'Biratnagar'),
('RSI', 'Red Sea International Airport'),
('AXA', 'Clayton J. Lloyd International'),
('BFL', 'Meadows Field'),
('DZA', 'Dzaoudzi–Pamandzi International'),
('LKN', 'Leknes'),
('DYG', 'Zhangjiajie Hehua International'),
('SOC', 'Adisumarmo International'),
('ZCO', 'La Araucanía International'),
('TMS', 'São Tomé International'),
('YXC', 'Cranbrook/Canadian Rockies International'),
('PVA', 'El Embrujo'),
('HAU', 'Haugesund Airport, Karmøy'),
('BFM', 'Mobile Downtown Airport'),
('SJI', 'San Jose'),
('OKI', 'Oki'),
('HJR', 'Khajuraho'),
('DRS', 'Dresden'),
('AQJ', 'King Hussein International'),
('BDJ', 'Syamsudin Noor International'),
('EZS', 'Elazığ'),
('AAR', 'Aarhus'),
('SZZ', 'Solidarity Szczecin–Goleniów'),
('CHO', 'Charlottesville–Albemarle'),
('OIT', 'Oita'),
('AQI', 'Al Qaisumah/Hafr Al Batin'),
('LUZ', 'Lublin'),
('TGG', 'Sultan Mahmud'),
('REU', 'Reus'),
('CND', 'Mihail Kogălniceanu International'),
('PKN', 'Iskandar'),
('VAS', 'Sivas'),
('LDU', 'Lahad Datu'),
('BVC', 'Aristides Pereira International'),
('HGR', 'Hagerstown Regional'),
('HOR', 'Horta'),
('TZL', 'Tuzla International'),
('KUA', 'Sultan Haji Ahmad Shah'),
('PGF', 'Perpignan–Rivesaltes'),
('AEY', 'Akureyri'),
('MWA', 'Williamson County Regional'),
('GLH', 'Mid Delta Regional'),
('JDO', 'Juazeiro do Norte'),
('GRJ', 'George'),
('BEN', 'Benina International'),
('IZA', 'Zona da Mata Regional'),
('ERH', 'Moulay Ali Cherif'),
('YYF', 'Penticton Regional'),
('JJD', 'Cruz Jericoacoara'),
('OGL', 'Ogle'),
('BLZ', 'Chileka International'),
('KTT', 'Kittilä'),
('PEG', 'San Francesco d Assisi'),
('PYG', 'Pakyong Airport'),
('QSR', 'Salerno / Pontecagnano Airport'),
('YSB', 'Sudbury'),
('CRM', 'Catarman National'),
('JSR', 'Jessore'),
('AOO', 'Altoona–Blair County'),
('EXT', 'Exeter'),
('KMJ', 'Kumamoto'),
('CDR', 'Chadron Municipal'),
('BHR', 'Bharatpur'),
('ANF', 'Andrés Sabella Gálvez International'),
('PJM', 'Puerto Jiménez'),
('INI', 'Niš Constantine the Great'),
('SSG', 'Malabo International'),
('HLA', 'Lanseria International'),
('KIT', 'Kithira Island National'),
('MLG', 'Abdul Rachman Saleh'),
('SFJ', 'Kangerlussuaq'),
('NOC', 'Ireland West Airport Knock'),
('NOS', 'Fascene'),
('SCN', 'Saarbrücken'),
('YDF', 'Deer Lake Regional'),
('BYO', 'Bonito'),
('AJF', 'Al-Jawf Domestic'),
('USN', 'Ulsan'),
('SMI', 'Samos International'),
('PNL', 'Pantelleria'),
('NLA', 'Simon Mwansa Kapwepwe International'),
('YSJ', 'Saint John'),
('FEG', 'Fergana International'),
('DRK', 'Drake Bay'),
('KTG', 'Ketapang Rahadi Osman'),
('SDY', 'Sidney–Richland Municipal'),
('MVY', 'Martha''s Vineyard'),
('PMR', 'Palmerston North'),
('AIA', 'Alliance Municipal'),
('ILM', 'Wilmington International'),
('SWQ', 'Sultan Muhammad Kaharuddin III'),
('CFB', 'Cabo Frio International'),
('AAZ', 'Quezaltenango Airport'),
('VDC', 'Vitória da Conquista'),
('SKZ', 'Sukkur'),
('YKO', 'Hakkari–Yüksekova'),
('LBB', 'Lubbock Preston Smith International'),
('OPS', 'Sinop'),
('AYP', 'Coronel FAP Alfredo Mendívil Duarte'),
('BHI', 'Comandante Espora'),
('CUK', 'Caye Caulker'),
('CYP', 'Calbayog'),
('GRO', 'Girona–Costa Brava'),
('LEA', 'RAAF Base Learmonth'),
('ASJ', 'Amami'),
('IXU', 'Aurangabad'),
('MHK', 'Manhattan Regional'),
('PWQ', 'Pavlodar'),
('VHC', 'Saurimo'),
('ZAZ', 'Zaragoza'),
('TYN', 'Taiyuan Wusu International'),
('OXB', 'Osvaldo Vieira International'),
('CXI', 'Cassidy International'),
('MHQ', 'Mariehamn'),
('YQG', 'Windsor International'),
('IXA', 'Agartala'),
('MUB', 'Maun'),
('BHU', 'Bhavnagar'),
('TCR', 'Tuticorin'),
('BRO', 'Brownsville/South Padre Island International'),
('AAE', 'Rabah Bitat'),
('HFE', 'Hefei Xinqiao International'),
('IBR', 'Ibaraki'),
('BHK', 'Bukhara International'),
('ADF', 'Adıyaman'),
('KNX', 'East Kimberley Regional'),
('LAN', 'Capital Region International'),
('LPI', 'Linköping City'),
('AGR', 'Agra'),
('TDD', 'Teniente Jorge Henrich Arauz'),
('SJW', 'Shijiazhuang Zhengding International'),
('MKY', 'Mackay'),
('RUT', 'Rutland–Southern Vermont Regional'),
('MYJ', 'Matsuyama'),
('JAF', 'Kankesanturai Airport'),
('AAN', 'Al Ain International'),
('HAH', 'Prince Said Ibrahim International'),
('DGH', 'Deoghar Airport'),
('RDO', 'Warsaw – Radom Airport'),
('SNO', 'Sakon Nakhon'),
('ALF', 'Alta'),
('IOA', 'Ioannina National'),
('RDP', 'Kazi Nazrul Islam'),
('HNM', 'Hana'),
('LUW', 'Bubung'),
('JKR', 'Janakpur'),
('KZO', 'Kyzylorda'),
('YZT', 'Port Hardy'),
('OSI', 'Osijek'),
('MAQ', 'Mae Sot'),
('CHH', 'Chachapoyas Airport'),
('LKE', 'Kenmore Air Harbor Seaplane Base'),
('BHJ', 'Bhuj'),
('PUF', 'Pau Pyrénées'),
('PHB', 'Parnaíba-Prefeito Dr. João Silva Filho International'),
('IEG', 'Zielona Góra'),
('KMI', 'Miyazaki'),
('PLW', 'Mutiara SIS Al-Jufrie'),
('IXD', 'Allahabad'),
('VCA', 'Can Tho International'),
('YNJ', 'Yanji Chaoyangchuan International'),
('CLY', 'Calvi – Sainte-Catherine'),
('LHW', 'Lanzhou Zhongchuan International'),
('KOP', 'Nakhon Phanom'),
('PGK', 'Depati Amir'),
('LXA', 'Lhasa Gonggar'),
('IZO', 'Izumo'),
('MSU', 'Mejametalana'),
('PFB', 'Lauro Kurtz'),
('HLZ', 'Hamilton'),
('LRH', 'La Rochelle – Île de Ré'),
('XUZ', 'Xuzhou Guanyin International'),
('MOL', 'Molde Airport, Årø'),
('CPC', 'Aviador Carlos Campos'),
('IFN', 'Isfahan International'),
('GHA', 'Noumérat – Moufdi Zakaria'),
('BZV', 'Maya-Maya'),
('TWT', 'Sanga-Sanga'),
('BRN', 'Bern'),
('AXT', 'Akita'),
('PDP', 'Capitán de Corbeta Carlos A. Curbelo International'),
('AJL', 'Lengpui'),
('REG', 'Reggio Calabria'),
('TBH', 'Tugdan'),
('BZG', 'Bydgoszcz Ignacy Jan Paderewski'),
('NKM', 'Nagoya Airfield'),
('ZLO', 'Playa de Oro International'),
('CPV', 'Campina Grande'),
('KGF', 'Sary-Arka'),
('OLX', 'Olkiombo Airstrip'),
('PCP', 'Príncipe Airport'),
('UKK', 'Oskemen'),
('YWH', 'Victoria Inner Harbour SPB'),
('VBY', 'Visby'),
('PLJ', 'Placencia'),
('DUJ', 'DuBois Regional'),
('PIN', 'Parintins'),
('CPO', 'Chamonate'),
('LSI', 'Sumburgh'),
('IRJ', 'La Rioja'),
('UME', 'Umeå'),
('LOK', 'Lodwar'),
('KRN', 'Kiruna'),
('MTB', 'Montelibano Airport'),
('CYA', 'Les Cayes Airport'),
('TIM', 'Mozes Kilangin International'),
('KIK', 'Kirkuk Air Base'),
('MKW', 'Rendani'),
('RSD', 'Rock Sound International'),
('DND', 'Dundee'),
('TMC', 'Tambolaka'),
('PMA', 'Pemba'),
('RAE', 'Arar Domestic'),
('LKY', 'Lake Manyara'),
('MCN', 'Middle Georgia Regional'),
('MOQ', 'Morondava'),
('LMC', 'La Macarena'),
('TUI', 'Turaif Domestic'),
('JGA', 'Jamnagar'),
('CZS', 'Cruzeiro do Sul International'),
('JSH', 'Sitia Public'),
('MRE', 'Mara Serena'),
('RJL', 'Logroño–Agoncillo'),
('YRT', 'Rankin Inlet'),
('MZG', 'Magong'),
('WEH', 'Weihai Dashuibo'),
('HOV', 'Ørsta–Volda Airport, Hovden'),
('LNK', 'Lincoln'),
('MRA', 'Misrata'),
('RBR', 'Rio Branco International'),
('ILY', 'Islay'),
('ESU', 'Essaouira-Mogador'),
('BFN', 'Bloemfontein'),
('YVO', 'Val-d Or'),
('PLX', 'Semey'),
('ACV', 'Arcata–Eureka'),
('PSR', 'Abruzzo'),
('CNM', 'Cavern City Air Terminal'),
('MYQ', 'Mysore'),
('PVC', 'Provincetown Municipal'),
('CSG', 'Columbus Metropolitan'),
('RSU', 'Yeosu'),
('ELU', 'Guemar'),
('SFG', 'Grand Case-Espérance'),
('BZL', 'Barisal'),
('TRG', 'Tauranga'),
('AMA', 'Rick Husband Amarillo International'),
('BDB', 'Bundaberg'),
('HYA', 'Barnstable Municipal'),
('SUX', 'Sioux Gateway'),
('CKZ', 'Çanakkale'),
('NCU', 'Nukus'),
('VII', 'Vinh International'),
('PQQ', 'Port Macquarie'),
('XAP', 'Chapecó'),
('KTN', 'Ketchikan International'),
('UEO', 'Kumejima'),
('CNQ', 'Doctor Fernando Piragine Niveyro International'),
('TOY', 'Toyama'),
('CDP', 'Cuddapah'),
('BBA', 'Balmaceda'),
('PXO', 'Porto Santo'),
('YTY', 'Yangzhou Taizhou International'),
('SKO', 'Sadiq Abubakar III International'),
('ABX', 'Albury'),
('AFA', 'San Rafael Airport'),
('IQQ', 'Diego Aracena International'),
('ADQ', 'Kodiak'),
('RER', 'Retalhuleu'),
('KVA', 'Kavala International'),
('EAT', 'Pangborn Memorial'),
('BME', 'Broome International'),
('PHE', 'Port Hedland International'),
('NEV', 'Vance W. Amory International'),
('UGC', 'Urgench International'),
('SWA', 'Jieyang Chaoshan International'),
('SUJ', 'Satu Mare International'),
('JIJ', 'Jijiga'),
('NTL', 'Newcastle'),
('URY', 'Gurayat Domestic'),
('LAE', 'Lae Nadzab'),
('GRK', 'Killeen–Fort Hood Regional'),
('JBR', 'Jonesboro Municipal'),
('ZUH', 'Zhuhai Jinwan'),
('TRW', 'Bonriki International'),
('ERC', 'Erzincan'),
('ERF', 'Erfurt–Weimar'),
('RJK', 'Rijeka'),
('IXS', 'Silchar'),
('CDT', 'Castellón–Costa Azahar'),
('BSA', 'Bosaso'),
('KDI', 'Haluoleo'),
('MLX', 'Malatya Erhaç'),
('YAZ', 'Tofino/Long Beach'),
('CPE', 'Campeche International'),
('RMI', 'Federico Fellini International'),
('MCE', 'Merced Regional'),
('GPI', 'Guapi'),
('ROI', 'Roi Et'),
('SUV', 'Nausori International'),
('SDD', 'Lubango'),
('ISA', 'Mount Isa'),
('MOF', 'Frans Xavier Seda'),
('DJB', 'Sultan Thaha'),
('TJK', 'Tokat'),
('TMM', 'Toamasina'),
('CSL', 'Cabo San Lucas International Airport'),
('GNB', 'Alpes–Isère'),
('HIN', 'Sacheon'),
('GGR', 'Garowe'),
('BEJ', 'Kalimarau'),
('PBR', 'Puerto Barrios'),
('WTB', 'Brisbane West Wellcamp'),
('BAY', 'Baia Mare Airport'),
('WRE', 'Whangarei'),
('SYY', 'Stornoway'),
('JLN', 'Joplin Regional'),
('GGG', 'East Texas Regional'),
('RJH', 'Shah Makhdum'),
('DIG', 'Diqing Shangri-La'),
('LLJ', 'Silampari Airport'),
('IVC', 'Invercargill'),
('ONQ', 'Caycuma'),
('SHL', 'Shillong'),
('SVO', 'Sheremetyevo International'),
('SAF', 'Santa Fe Municipal'),
('KSN', 'Kostanay'),
('CZX', 'Changzhou Benniu'),
('UNN', 'Ranong'),
('ZNA', 'Nanaimo Harbour'),
('BEK', 'Bareilly Airport'),
('JOE', 'Joensuu'),
('MIU', 'Maiduguri International Airport'),
('KHS', 'Khasab'),
('YOL', 'Yola'),
('TOE', 'Tozeur–Nefta International'),
('VAA', 'Vaasa'),
('MBI', 'Mbeya'),
('FAY', 'Fayetteville Regional'),
('TAY', 'Tartu'),
('DLH', 'Duluth International'),
('VCS', 'Con Dao'),
('BTR', 'Baton Rouge Metropolitan'),
('EEA', 'Planalto Serrano Regional Airport'),
('KSE', 'Kasese'),
('TMI', 'Tumlingtar'),
('RIA', 'Santa Maria'),
('AJR', 'Arvidsjaur'),
('MST', 'Maastricht Aachen'),
('BMU', 'Sultan Muhammad Salahudin'),
('MBT', 'Moises R. Espinosa'),
('BWX', 'Blimbingsari'),
('URG', 'Ruben Berta International'),
('GAJ', 'Yamagata'),
('LEN', 'León'),
('OMH', 'Urmia'),
('GLF', 'Golfito'),
('LRM', 'La Romana International'),
('BDO', 'Husein Sastranegara International'),
('YQX', 'Gander International'),
('MFA', 'Mafia'),
('LDY', 'City of Derry'),
('IXG', 'Belgaum'),
('FUN', 'Funafuti International'),
('ERS', 'Eros'),
('GWD', 'Gwadar International'),
('SHM', 'Nanki–Shirahama'),
('BAL', 'Batman'),
('HZG', 'Hanzhong Xiguan'),
('KWJ', 'Gwangju'),
('SFA', 'Sfax–Thyna International'),
('PDV', 'Plovdiv'),
('IMF', 'Imphal International'),
('DAB', 'Daytona Beach International'),
('CMG', 'Corumbá International'),
('EUN', 'Hassan I'),
('RDD', 'Redding Municipal'),
('MVF', 'Mossoro'),
('NDU', 'Rundu'),
('GDV', 'Dawson Community'),
('ANA', 'Maasai Mara Angama'),
('MHC', 'Mocopulli'),
('KSY', 'Kars Harakani'),
('GAN', 'RAF Gan'),
('ARM', 'Armidale'),
('YWK', 'Wabush'),
('PDA', 'César Gaviria Trujillo'),
('LLO', 'Palopo Lagaligo'),
('JIK', 'Ikaria Island National'),
('CHX', 'Changuinola Capitán Manuel Niño International'),
('IXY', 'Kandla'),
('ALW', 'Walla Walla Regional'),
('BDU', 'Bardufoss'),
('LRS', 'Leros Municipal'),
('ENE', 'H. Hasan Aroeboesman'),
('OSR', 'Leoš Janáček Airport Ostrava'),
('WMI', 'Warsaw Modlin'),
('OMR', 'Oradea International'),
('YEV', 'Inuvik (Mike Zubko)'),
('TJQ', 'H.A.S. Hanandjoeddin International'),
('JJN', 'Quanzhou Jinjiang International'),
('BTC', 'Batticaloa'),
('VXO', 'Växjö Småland'),
('CRP', 'Corpus Christi International'),
('CSK', 'Cap Skirring'),
('DGA', 'Dangriga'),
('GEL', 'Sepé Tiaraju'),
('PET', 'Pelotas International'),
('SON', 'Santo-Pekoa International'),
('ZHA', 'Zhanjiang'),
('CBH', 'Boudghene Ben Ali Lotfi'),
('MUH', 'Mersa Matruh Airport'),
('MMB', 'Memanbetsu'),
('APL', 'Nampula'),
('YBG', 'CFB Bagotville'),
('KGI', 'Kalgoorlie-Boulder'),
('MPN', 'RAF Mount Pleasant'),
('KOI', 'Kirkwall'),
('TLU', 'Golfo de Morrosquillo'),
('KHG', 'Kashi'),
('DHI', 'Dhangadhi'),
('SKU', 'Skyros Island National'),
('GUC', 'Gunnison–Crested Butte Regional'),
('BQB', 'Busselton Regional'),
('VCL', 'Chu Lai International'),
('SZK', 'Skukuza'),
('KUO', 'Kuopio'),
('ATM', 'Altamira'),
('DZN', 'Zhezkazgan'),
('GNJ', 'Ganja International Airport'),
('TLE', 'Toliara'),
('SJZ', 'Sao Jorge'),
('KMQ', 'Komatsu'),
('AUQ', 'Atuona'),
('FRO', 'Florø'),
('GPA', 'Araxos'),
('ALH', 'Albany'),
('GNM', 'Guanambi Airport'),
('TLM', 'Zenata – Messali El Hadj'),
('PRI', 'Praslin Island'),
('THD', 'Thanh Hoa Tho Xuan'),
('DTB', 'Silangit International'),
('NQU', 'Reyes Murillo'),
('RFP', 'Raiatea'),
('LYB', 'Edward Bodden Airfield'),
('LXS', 'Lemnos International'),
('TNJ', 'Raja Haji Fisabilillah International'),
('EGE', 'Eagle County Regional'),
('OGD', 'Ogden-Hinckley'),
('IRI', 'Iringa Airport'),
('FDH', 'Friedrichshafen'),
('SGU', 'St. George Regional'),
('MBS', 'MBS International'),
('TKD', 'Takoradi'),
('GGM', 'Kakamega'),
('KIM', 'Kimberley'),
('SVU', 'Savusavu'),
('FEC', 'Feira de Santana'),
('AXD', 'Alexandroupolis International'),
('GYS', 'Guangyuan Panlong'),
('CZU', 'Las Brujas'),
('PPB', 'Presidente Prudente'),
('OKJ', 'Okayama'),
('KKJ', 'Kitakyushu'),
('PAD', 'Paderborn Lippstadt'),
('CYB', 'Charles Kirkconnell International'),
('ARX', 'Aracati Airport'),
('TTT', 'Taitung'),
('HLN', 'Helena Regional'),
('WVB', 'Walvis Bay'),
('MKM', 'Mukah'),
('GOU', 'Garoua International'),
('KUH', 'Kushiro'),
('XSP', 'Seletar Airport'),
('PRA', 'General Justo José de Urquiza'),
('AZS', 'Samaná El Catey International'),
('DMU', 'Dimapur'),
('OST', 'Ostend-Bruges International'),
('TVU', 'Matei'),
('CFS', 'Coffs Harbour'),
('HIR', 'Honiara International'),
('DWD', 'Dawadmi Domestic'),
('OKD', 'Okadama'),
('KUV', 'Gunsan'),
('KKX', 'Kikai'),
('PCR', 'Germán Olano'),
('HYN', 'Taizhou Luqiao'),
('BHE', 'Woodbourne'),
('YBR', 'Brandon Municipal'),
('SFN', 'Sauce Viejo'),
('BSC', 'Jose Celestino Mutis'),
('YCO', 'Kugluktuk'),
('UBJ', 'Yamaguchi Ube'),
('MBZ', 'Maués Airport'),
('PXU', 'Pleiku'),
('DJG', 'Tiska'),
('OAJ', 'Albert J. Ellis'),
('QSF', 'Ain Arnat'),
('RKV', 'Reykjavík'),
('HEA', 'Herat International'),
('FLW', 'Flores'),
('SSJ', 'Sandnessjøen Airport, Stokka'),
('SHW', 'Sharurah Domestic'),
('ASE', 'Aspen–Pitkin County'),
('REL', 'Almirante Marcos A. Zar'),
('AOE', 'Anadolu'),
('CRD', 'General Enrique Mosconi International'),
('PGZ', 'Ponta Grossa A.Amilton Beraldo'),
('MMJ', 'Matsumoto'),
('AAX', 'Araxá'),
('XFN', 'Xiangyang Liuji'),
('NMA', 'Namangan'),
('RRJ', 'Jacarepaguá Airport'),
('OLF', 'L. M. Clayton'),
('YBK', 'Baker Lake'),
('TJH', 'Toyooka'),
('ROK', 'Rockhampton'),
('GDQ', 'Gondar'),
('BSK', 'Biskra'),
('TTE', 'Babullah'),
('BBK', 'Kasane'),
('FMA', 'Formosa International'),
('HGU', 'Mount Hagen'),
('BHH', 'Bisha Domestic'),
('ASV', 'Amboseli'),
('DIR', 'Aba Tenna Dejazmach Yilma International'),
('VDE', 'El Hierro'),
('NDB', 'Nouadhibou International'),
('JHG', 'Xishuangbanna Gasa'),
('CFE', 'Clermont-Ferrand Auvergne'),
('STC', 'St. Cloud Regional'),
('CRV', 'Crotone Airport'),
('XNN', 'Xining Caojiabao International'),
('SCE', 'University Park'),
('YDA', 'Dawson City'),
('KSF', 'Kassel'),
('KLH', 'Kolhapur Airport'),
('SDL', 'Sundsvall–Timrå'),
('KVO', 'Morava Airport'),
('FSP', 'Saint-Pierre'),
('DJJ', 'Sentani International'),
('YTS', 'Timmins/Victor M. Power'),
('YUM', 'Yuma International'),
('TIU', 'Timaru'),
('GRW', 'Graciosa'),
('NOP', 'Sinop'),
('AJI', 'Ağrı'),
('WGP', 'Umbu Mehang Kunda'),
('ART', 'Watertown International'),
('GZO', 'Nusatupe'),
('JNG', 'Jining Qufu'),
('TBB', 'Dong Tac'),
('MFU', 'Mfuwe'),
('ABS', 'Abu Simbel'),
('CEL', 'Canela Airport'),
('HMV', 'Hemavan'),
('DOY', 'Dongying Shengli'),
('YQZ', 'Quesnel'),
('RNJ', 'Yoron'),
('TTJ', 'Tottori'),
('VIJ', 'Virgin Gorda'),
('RMA', 'Roma'),
('LPT', 'Lampang'),
('AGS', 'Augusta Regional'),
('OLA', 'Ørland Main Air Station'),
('YHK', 'Gjoa Haven'),
('TBT', 'Tabatinga International'),
('HVR', 'Havre City–County'),
('EGS', 'Egilsstaðir'),
('LIG', 'Limoges – Bellegarde'),
('XWA', 'Williston Basin International Airport'),
('CAB', 'Cabinda'),
('PGH', 'Pantnagar'),
('WJR', 'Wajir'),
('WMX', 'Wamena'),
('CXJ', 'Campo dos Bugres'),
('MGB', 'Mount Gambier'),
('ANX', 'Andøya'),
('ONS', 'Onslow'),
('MEI', 'Meridian Regional'),
('MUE', 'Waimea-Kohala'),
('GIU', 'Sigiriya'),
('CLD', 'McClellan–Palomar'),
('BEB', 'Benbecula'),
('AFL', 'Alta Floresta'),
('KRP', 'Midtjyllands'),
('NRN', 'Weeze'),
('CYS', 'Cheyenne Regional'),
('HUU', 'Alférez FAP David Figueroa Fernandini'),
('KME', 'Kamembe'),
('SKH', 'Surkhet Airport'),
('JRG', 'Jharsuguda Airport'),
('BVE', 'Brive–Souillac Airport'),
('SMA', 'Santa Maria'),
('GJA', 'La Laguna Airport'),
('SHI', 'Shimojishima Airport'),
('HFT', 'Hammerfest'),
('PMY', 'El Tehuelche'),
('TGT', 'Tanga'),
('RSA', 'Santa Rosa'),
('SCC', 'Deadhorse'),
('NNT', 'Nan Nakhon'),
('ALP', 'Aleppo International Airport'),
('EQS', 'Esquel'),
('MMH', 'Mammoth Yosemite'),
('YGR', 'Îles-de-la-Madeleine'),
('PIX', 'Pico'),
('SJT', 'San Angelo Regional'),
('MBE', 'Monbetsu'),
('NYU', 'Nyaung U'),
('CME', 'Ciudad del Carmen International'),
('TIN', 'Tindouf'),
('INU', 'Nauru International'),
('KEU', 'Maasai Mara Keekorok'),
('RVE', 'Los Colonizadores'),
('ETZ', 'Metz–Nancy–Lorraine'),
('FRW', 'Francistown'),
('HDN', 'Yampa Valley'),
('BND', 'Bandar Abbas International'),
('OER', 'Örnsköldsvik'),
('AKN', 'King Salmon'),
('MJN', 'Amborovy'),
('LXG', 'Louang Namtha'),
('DQM', 'Duqm Jaaluni'),
('YPW', 'Powell River'),
('JSY', 'Syros Island National'),
('FON', 'Fortuna Arenal'),
('LFT', 'Lafayette Regional'),
('POJ', 'Patos de Minas Airport'),
('HUH', 'Huahine – Fare'),
('TMR', 'Aguenar – Hadj Bey Akhamok'),
('YIH', 'Yichang Sanxia'),
('YQY', 'Sydney/J.A. Douglas McCurdy'),
('NNY', 'Nanyang Jiangying'),
('YGZ', 'Grise Fiord'),
('UAK', 'Narsarsuaq'),
('NAW', 'Narathiwat'),
('LBC', 'Lubeck Blankensee Airport'),
('DUE', 'Dundo'),
('NSB', 'New Smyrna Beach Municipal Airport'),
('ZGI', 'Gods River'),
('BAZ', 'Barcelos Airport'),
('BRW', 'Wiley Post–Will Rogers Memorial'),
('KLV', 'Karlovy Vary'),
('KAO', 'Kuusamo'),
('YRB', 'Resolute Bay'),
('BIK', 'Frans Kaisiepo International'),
('LGI', 'Deadman''s Cay'),
('MQN', 'Mo i Rana Airport, Røssvoll'),
('UAQ', 'Domingo Faustino Sarmiento'),
('SUN', 'Friedman Memorial'),
('LGG', 'Liège'),
('AWA', 'Awasa'),
('SLI', 'Solwezi'),
('BWK', 'Brač'),
('YIN', 'Yining'),
('SWL', 'San Vicente Airport'),
('ELD', 'South Arkansas Regional Airport at Goodwin Field'),
('SXZ', 'Siirt'),
('CJM', 'Chumphon'),
('JPR', 'Ji-Paraná'),
('GOV', 'Gove'),
('YTH', 'Thompson'),
('KDV', 'Vunisea'),
('YCY', 'Clyde River'),
('HKR', 'Mara North Airport'),
('DRV', 'Dharavandhoo'),
('YOJ', 'High Level'),
('TFL', 'Teófilo Otoni Airport'),
('JKL', 'Kalymnos Island National'),
('LFQ', 'Linfen Qiaoli'),
('SLW', 'Plan de Guadalupe International'),
('WKJ', 'Wakkanai'),
('GIS', 'Gisborne'),
('YKM', 'Yakima Air Terminal'),
('VLL', 'Valladolid'),
('FSM', 'Fort Smith Regional'),
('RST', 'Rochester International'),
('SJL', 'Sao Gabriel'),
('CLL', 'Easterwood'),
('DIN', 'Dien Bien Phu'),
('DPO', 'Devonport'),
('GDT', 'JAGS McCartney International'),
('BRA', 'Barreiras'),
('CFN', 'Donegal'),
('DIB', 'Dibrugarh'),
('BRB', 'Barreirinhas Airport'),
('YEI', 'Yenişehir'),
('KOW', 'Ganzhou Huangjin'),
('LZN', 'Matsu Nangan'),
('JZH', 'Jiuzhai Huanglong'),
('YYE', 'Fort Nelson'),
('MIM', 'Merimbula'),
('LEC', 'Lençóis'),
('BOY', 'Bobo Dioulasso'),
('PBO', 'Paraburdoo'),
('DBO', 'Dubbo City Regional'),
('SMS', 'Sainte Marie'),
('MSZ', 'Namibe'),
('TRR', 'China Bay'),
('GET', 'Geraldton'),
('COD', 'Yellowstone Regional'),
('SDE', 'Vicecomodoro Ángel de la Paz Aragonés'),
('YVB', 'Bonaventure'),
('RRG', 'Sir Gaëtan Duval'),
('WAG', 'Whanganui Airport'),
('DLG', 'Dillingham'),
('YCB', 'Cambridge Bay'),
('NTG', 'Nantong Xingdong'),
('BNK', 'Ballina Byron Gateway'),
('KJB', 'Kurnool Airport'),
('MOZ', 'Moorea'),
('KAJ', 'Kajaani'),
('SLN', 'Salina Regional'),
('AAP', 'APT Pranoto Airport'),
('GRQ', 'Groningen Airport Eelde'),
('WIN', 'Winton'),
('KGC', 'Kingscote'),
('RGI', 'Rangiroa'),
('GTZ', 'Grumeti Kirawira B'),
('GTO', 'Jalaluddin'),
('KAZ', 'Kaubang'),
('JUZ', 'Quzhou'),
('PPK', 'Petropavl'),
('MOB', 'Mobile Regional'),
('TRK', 'Juwata International'),
('LMN', 'Limbang'),
('YNZ', 'Yancheng Nanyang International'),
('ROO', 'Rondonópolis'),
('TGR', 'Sidi Mahdi'),
('MIG', 'Mianyang Nanjiao'),
('YVQ', 'Norman Wells'),
('PPQ', 'Kapiti Coast'),
('TET', 'Chingozi'),
('MYT', 'Myitkyina'),
('ACI', 'Alderney'),
('VNX', 'Vilankulo'),
('CKS', 'Carajás'),
('LEU', 'Andorra–La Seu d''Urgell Airport'),
('PTG', 'Polokwane International'),
('YIC', 'Yichun Mingyueshan'),
('VGZ', 'Villa Garzón'),
('IPT', 'Williamsport Regional'),
('GWT', 'Sylt'),
('YRL', 'Red Lake'),
('LMU', 'Letung Airport'),
('HVB', 'Hervey Bay'),
('HVD', 'Khovd'),
('AGT', 'Guaraní International'),
('RES', 'Resistencia International'),
('SET', 'Serra Talhada Airport'),
('NWI', 'Norwich'),
('MTJ', 'Montrose Regional'),
('TEQ', 'Tekirdağ Çorlu'),
('DRO', 'Durango–La Plata County'),
('JTC', 'Bauru-Arealva'),
('JAV', 'Ilulissat'),
('ARD', 'Alor Island'),
('ACT', 'Waco Regional'),
('LNZ', 'Linz'),
('MBX', 'Maribor Edvard Rusjan'),
('MME', 'Durham Tees Valley'),
('PKY', 'Tjilik Riwut'),
('TKN', 'Tokunoshima'),
('ITH', 'Ithaca Tompkins Regional'),
('RRS', 'Røros'),
('BOH', 'Bournemouth'),
('DHN', 'Dothan Regional'),
('ZYI', 'Zunyi Xinzhou'),
('ZWL', 'Wollaston Lake Airport'),
('ZUM', 'Churchill Falls'),
('ZTM', 'Shamattawa'),
('ZTB', 'Tête-à-la-Baleine'),
('ZTA', 'Tureia'),
('ZSJ', 'Sandy Lake'),
('ZSE', 'Pierrefonds'),
('ZSA', 'San Salvador'),
('ZQZ', 'Zhangjiakou Ningyuan'),
('ZPB', 'Sachigo Lake'),
('ZOS', 'Cañal Bajo Carlos Hott Siebert'),
('ZNE', 'Newman'),
('ZMT', 'Masset'),
('ZLT', 'La Tabatière'),
('ZKE', 'Kashechewan'),
('ZIG', 'Ziguinchor'),
('ZIA', 'Zhukovsky International'),
('ZHY', 'Zhongwei Shapotou'),
('ZGU', 'Gaua'),
('ZGS', 'La Romaine'),
('ZFD', 'Fond-du-Lac Airport'),
('ZEM', 'Eastmain River'),
('ZEL', 'Bella Bella (Campbell Island)'),
('ZBL', 'Thangool'),
('ZBF', 'Bathurst'),
('ZAT', 'Zhaotong'),
('ZAL', 'Pichoy Airport'),
('ZAC', 'York Landing'),
('YZZ', 'Trail'),
('YZY', 'Zhangye Ganzhou'),
('YZV', 'Sept-Îles'),
('YZS', 'Coral Harbour'),
('YZP', 'Sandspit'),
('YZG', 'Salluit'),
('YYY', 'Mont-Joli'),
('YYR', 'CFB Goose Bay'),
('YYQ', 'Churchill'),
('YYH', 'Taloyoak'),
('YYD', 'Smithers'),
('YYB', 'North Bay/Jack Garland'),
('YYA', 'Yueyang Sanhe Airport'),
('YXP', 'Pangnirtung'),
('YXN', 'Whale Cove'),
('YXL', 'Sioux Lookout'),
('YWS', 'Whistler'),
('YWL', 'Williams Lake'),
('YWB', 'Kangiqsujuaq (Wakeham Bay)'),
('YVZ', 'Deer Lake'),
('YVP', 'Kuujjuaq'),
('YVM', 'Qikiqtarjuaq'),
('YVC', 'La Ronge (Barber Field) Airport'),
('YUY', 'Rouyn-Noranda'),
('YUX', 'Hall Beach'),
('YUT', 'Naujaat'),
('YUS', 'Yushu Batang'),
('YUD', 'Umiujaq'),
('YTQ', 'Tasiujaq'),
('YTL', 'Big Trout Lake Airport'),
('YTE', 'Cape Dorset'),
('YST', 'St. Theresa Point'),
('YSQ', 'Songyuan Chaganhu'),
('YSO', 'Postville'),
('YSK', 'Sanikiluaq'),
('YSF', 'Stony Rapids Airport'),
('YRS', 'Red Sucker Lake'),
('YRG', 'Rigolet'),
('YQK', 'Kenora'),
('YQD', 'The Pas'),
('YQC', 'Quaqtaq'),
('YPX', 'Puvirnituq'),
('YPR', 'Prince Rupert'),
('YPO', 'Peawanuck'),
('YPM', 'Pikangikum'),
('YPL', 'Pickle Lake Airport'),
('YPJ', 'Aupaluk'),
('YPH', 'Inukjuak'),
('YPA', 'Prince Albert (Glass Field) Airport'),
('YOH', 'Oxford House'),
('YOC', 'Old Crow'),
('YNS', 'Nemiscau'),
('YNP', 'Natuashish'),
('YNO', 'North Spirit Lake'),
('YNL', 'Points North Landing Airport'),
('YNE', 'Norway House'),
('YNC', 'Wemindji'),
('YNA', 'Natashquan'),
('YMT', 'Chibougamau/Chapais'),
('YMO', 'Moosonee'),
('YMN', 'Makkovik'),
('YLL', 'Lloydminster'),
('YLC', 'Kimmirut'),
('YKU', 'Chisasibi'),
('YKS', 'Yakutsk'),
('YKQ', 'Waskaganish'),
('YKL', 'Schefferville'),
('YKH', 'Yingkou Lanqi'),
('YKG', 'Kangirsuk'),
('YIV', 'Island Lake'),
('YIO', 'Pond Inlet'),
('YIK', 'Ivujivik'),
('YIF', 'Saint-Augustin'),
('YIE', 'Arxan Yi''ershi'),
('YHY', 'Hay River/Merlyn Carter'),
('YHU', 'Montreal Saint-Hubert Longueuil'),
('YHS', 'Sechelt'),
('YHR', 'Chevery'),
('YHP', 'Poplar Hill Airport'),
('YHO', 'Hopedale'),
('YHI', 'Ulukhaktok/Holman'),
('YHD', 'Dryden Regional'),
('YGX', 'Gillam'),
('YGW', 'Kuujjuarapik'),
('YGT', 'Igloolik'),
('YGP', 'Michel-Pouliot Gaspé'),
('YGO', 'Gods Lake Narrows'),
('YGL', 'La Grande Rivière'),
('YGG', 'Ganges Harbor'),
('YFS', 'Fort Simpson'),
('YFO', 'Flin Flon'),
('YFA', 'Fort Albany'),
('YER', 'Fort Severn Airport'),
('YEK', 'Arviat'),
('YDP', 'Nain'),
('YCU', 'Yuncheng Guangong'),
('YCS', 'Chesterfield Inlet'),
('YCR', 'Cross Lake (Charlie Sinclair Memorial)'),
('YCG', 'West Kootenay Regional'),
('YBX', 'Lourdes-de-Blanc-Sablon'),
('YBT', 'Brochet'),
('YBP', 'Yibin Caiba'),
('YBE', 'Uranium City Airport'),
('YBC', 'Baie-Comeau'),
('YBB', 'Kugaaruk'),
('YAY', 'St. Anthony'),
('YAX', 'Wapekeka Airport'),
('YAT', 'Attawapiskat'),
('YAP', 'Yap International'),
('YAM', 'Sault Ste. Marie'),
('YAK', 'Yakutat'),
('YAG', 'Fort Frances Municipal'),
('YAB', 'Arctic Bay'),
('YAA', 'Anahim Lake'),
('XTL', 'Tadoule Lake'),
('XTG', 'Thargomindah'),
('XSI', 'South Indian Lake'),
('XSC', 'South Caicos'),
('XMY', 'Yam Island Airport'),
('XMH', 'Manihi'),
('XLS', 'Saint Louis Airport'),
('XLB', 'Lac Brochet'),
('XKS', 'Kasabonika Airport'),
('XIL', 'Xilinhot'),
('XIC', 'Xichang Qingshan'),
('XGR', 'Kangiqsualujjuaq (Georges River)'),
('XCR', 'Châlons Vatry'),
('XCH', 'Christmas Island'),
('XBE', 'Bearskin Lake'),
('XAI', 'Xinyang Minggang Airport'),
('WYS', 'Yellowstone'),
('WYA', 'Whyalla'),
('WXN', 'Wanzhou Wuqiao'),
('WWK', 'Wewak'),
('WUZ', 'Changzhoudao Airport'),
('WUT', 'Xinzhou Wutaishan'),
('WUS', 'Wuyishan'),
('WUA', 'Wuhai'),
('WSZ', 'Westport'),
('WSK', 'Chongqing Wushan Airport'),
('WRZ', 'Weerawila'),
('WRY', 'Westray'),
('WRG', 'Wrangell'),
('WPU', 'Guardiamarina Zañartu'),
('WPR', 'Capitan Fuentes Martinez'),
('WOL', 'Illawarra Regional'),
('WNR', 'Windorah'),
('WNN', 'Wunnumin Lake Airport'),
('WNH', 'Wenshan Puzhehei'),
('WMT', 'Zunyi Maotai Airport'),
('WMN', 'Maroantsetra'),
('WLS', 'Hihifo'),
('WLH', 'Walaha'),
('WJU', 'Wonju'),
('WIC', 'Wick'),
('WHK', 'Whakatane'),
('WGN', 'Shaoyang Wugang'),
('WGA', 'Wagga Wagga'),
('WEI', 'Weipa'),
('WDS', 'Shiyan Wudangshan'),
('WBM', 'Wapenamanda'),
('WAE', 'Wadi al-Dawasir Domestic'),
('VXC', 'Lichinga'),
('VVZ', 'Takhamalt'),
('VVO', 'Vladivostok International'),
('VST', 'Stockholm Västerås'),
('VSE', 'Viseu'),
('VRL', 'Vila Real'),
('VPY', 'Chimoio'),
('VPG', 'Vipingo'),
('VPE', 'Ondjiva Pereira'),
('VOL', 'Nea Anchialos National'),
('VOG', 'Volgograd International'),
('VLD', 'Valdosta Regional'),
('VKO', 'Vnukovo International'),
('VKG', 'Rach Gia'),
('VJB', 'Xai-Xai Airport'),
('VIT', 'Vitoria'),
('VHM', 'Vilhelmina'),
('VEY', 'Vestmannaeyjar Airport'),
('VDZ', 'Valdez'),
('VDS', 'Vadsø'),
('VDM', 'Gobernador Edgardo Castello'),
('VCT', 'Victoria Regional'),
('VBV', 'Vanuabalavu'),
('VAW', 'Vardø Airport, Svartnes'),
('VAV', 'Vavaʻu International'),
('VAO', 'Suavanao'),
('VAI', 'Vanimo'),
('VAG', 'Major Brigadeiro Trompowsky'),
('UZR', 'Urdzhar'),
('UYN', 'Yulin Yuyang'),
('UVE', 'Ouvéa'),
('UUS', 'Yuzhno-Sakhalinsk'),
('UUD', 'Baikal International'),
('UTT', 'Mthatha'),
('UTN', 'Upington'),
('UPK', 'Upernavik Kujalleq Heliport'),
('UNK', 'Unalakleet'),
('UNG', 'Kiunga'),
('UNA', 'Una-Comandatuba Airport'),
('UMD', 'Uummannaq Heliport'),
('ULZ', 'Donoi'),
('ULP', 'Quilpie'),
('ULO', 'Ulaangom'),
('ULG', 'Ölgii'),
('ULB', 'Ulei'),
('UFA', 'Ufa International'),
('UEL', 'Quelimane'),
('UCB', 'Ulanqab Jining'),
('UBA', 'Uberaba'),
('UAS', 'Samburu'),
('UAP', 'Ua Pou'),
('UAH', 'Ua Huka'),
('TYR', 'Tyler Pounds Regional'),
('TYF', 'Torsby'),
('TXN', 'Huangshan Tunxi International'),
('TXK', 'Texarkana Regional'),
('TWF', 'Magic Valley Regional'),
('TWC', 'Tumxuk Tangwangcheng Airport'),
('TVY', 'Dawei'),
('TVS', 'Tangshan Sannühe'),
('TUO', 'Taupo'),
('TUK', 'Turbat International'),
('TUF', 'Tours Val de Loire'),
('TUB', 'Tubuai – Mataura'),
('TTQ', 'Tortuguero'),
('TTA', 'Tan Tan'),
('TSJ', 'Tsushima'),
('TRE', 'Tiree'),
('TPS', 'Vincenzo Florio Airport Trapani–Birgi'),
('TOF', 'Bogashevo'),
('TOB', 'Tobruk'),
('TNN', 'Tainan'),
('TNH', 'Tonghua Sanyuanpu'),
('TNE', 'New Tanegashima'),
('TMX', 'Timimoun'),
('TMW', 'Tamworth'),
('TMT', 'Trombetas'),
('TMP', 'Tampere–Pirkkala'),
('TMJ', 'Termez'),
('TMF', 'Thimarafushi'),
('TME', 'Gabriel Vargas Santos'),
('TLQ', 'Turpan Jiaohe'),
('TLI', 'Sultan Bantilan'),
('TKX', 'Takaroa'),
('TKS', 'Tokushima'),
('TKQ', 'Kigoma'),
('TKP', 'Takapoto'),
('TKK', 'Chuuk International'),
('TKE', 'Tenakee Seaplane Base'),
('TJS', 'Tanjung Harapan'),
('TJL', 'Três Lagoas'),
('TIZ', 'Tari'),
('TIH', 'Tikehau'),
('TID', 'Abdelhafid Boussouf Bou Chekif'),
('THU', 'Thule Air Base'),
('THS', 'Sukhothai'),
('THL', 'Tachilek'),
('TGO', 'Tongliao'),
('TGI', 'Tingo María'),
('TGC', 'Tanjung Manis'),
('TFF', 'Tefé'),
('TEZ', 'Tezpur'),
('TEN', 'Tongren Fenghuang'),
('TEE', 'Cheikh Larbi Tebessi'),
('TDK', 'Taldykorgan'),
('TCZ', 'Tengchong Tuofeng'),
('TCG', 'Tacheng'),
('TCD', 'Coposa'),
('TCA', 'Tennant Creek'),
('TBO', 'Tabora'),
('TBG', 'Tabubil'),
('TAT', 'Poprad–Tatry'),
('TAH', 'Whitegrass'),
('SZY', 'Olsztyn-Mazury'),
('SZE', 'Semera'),
('SZA', 'Soyo'),
('SYU', 'Warraber Island Airport'),
('SYO', 'Shonai'),
('SYM', 'Pu er Simao'),
('SXK', 'Saumlaki Olilit'),
('SWP', 'Swakopmund Airport'),
('SWO', 'Stillwater Regional'),
('SWJ', 'South West Bay'),
('SVX', 'Koltsovo'),
('SVI', 'Eduardo Falla Solano Airport'),
('SVB', 'Sambava'),
('SUR', 'Summer Beaver Airport'),
('SSR', 'Sara'),
('SRK', 'Siorapaluk Heliport'),
('SRA', 'Santa Rosa Airport'),
('SQJ', 'Sanming Shaxian'),
('SQG', 'Sintang'),
('SQD', 'Shangrao Sanqingshan'),
('SPY', 'San Pédro'),
('SPS', 'Wichita Falls Municipal'),
('SPP', 'Menongue'),
('SOY', 'Stronsay'),
('SOJ', 'Sørkjosen'),
('SOG', 'Sogndal Airport, Haukåsen'),
('SNW', 'Thandwe'),
('SNP', 'St. Paul Island'),
('SMT', 'Sorriso'),
('SMQ', 'H. Asan'),
('SLM', 'Salamanca'),
('SLH', 'Vanua Lava'),
('SKN', 'Stokmarknes Airport, Skagen'),
('SJK', 'Aeroporto Internacional de São José dos Campos'),
('SJE', 'Jorge Enrique González Torres'),
('SIT', 'Sitka Rocky Gutierrez'),
('SIS', 'Sishen'),
('SIF', 'Simara'),
('SHS', 'Shashi'),
('SHR', 'Sheridan County Airport'),
('SHF', 'Shihezi Huayuan'),
('SHC', 'Shire'),
('SHB', 'Nakashibetsu'),
('SGY', 'Skagway'),
('SGX', 'Songea'),
('SGO', 'St George'),
('SGG', 'Sermiligaaq Heliport'),
('SGD', 'Sønderborg'),
('SEB', 'Sabha'),
('SDP', 'Sand Point'),
('SDN', 'Sandane Airport, Anda'),
('SCZ', 'Santa Cruz/Graciosa Bay/Luova'),
('SCR', 'Scandinavian Mountains Airport'),
('SCF', 'Phoenix Scottsdale Airport'),
('SBY', 'Salisbury–Ocean City–Wicomico Regional'),
('SBR', 'Saibai Island'),
('SAU', 'Sawu Airport'),
('SAB', 'Juancho E. Yrausquin'),
('RYL', 'Lower Zambezi Nat.Park Royal'),
('RVV', 'Raivavae'),
('RVR', 'Green River Municipal Airport'),
('RVK', 'Rørvik Airport, Ryum'),
('RVD', 'Rio Verde'),
('RUR', 'Rurutu'),
('RUL', 'Maavarulu Airport'),
('RTG', 'Frans Sales Lega'),
('RTA', 'Rotuma'),
('RRR', 'Raroia'),
('RQA', 'Ruoqiang Loulan Airport'),
('ROW', 'Roswell International Air Center'),
('ROT', 'Rotorua Regional'),
('RNL', 'Rennell/Tingoa'),
('RNB', 'Ronneby'),
('RNA', 'Ulawa'),
('RMT', 'Rimatara'),
('RLO', 'Valle del Conlara Airport'),
('RLK', 'Bayannur Tianjitai'),
('RLG', 'Rostock–Laage'),
('RKZ', 'Shigatse Peace'),
('RKS', 'Rock Springs–Sweetwater County'),
('RKE', 'Roskilde'),
('RKD', 'Knox County Regional'),
('RKA', 'Aratika-Nord'),
('RJB', 'Rajbiraj Airport'),
('RIZ', 'Rizhao Shanzihe'),
('RIW', 'Riverton Regional'),
('RIS', 'Rishiri'),
('RIH', 'Aeropuerto Internacional Cap. Scarlet Martínez'),
('RIB', 'Riberalta'),
('RHI', 'Rhinelander–Oneida County'),
('RHD', 'Las Termas'),
('RGS', 'Burgos Airport'),
('RGL', 'Piloto Civil Norberto Fernández International'),
('RGA', 'Hermes Quijada International'),
('RET', 'Røst'),
('RDZ', 'Rodez–Aveyron'),
('RCU', 'Las Higueras'),
('RCQ', 'Reconquista'),
('RCM', 'Richmond'),
('RCB', 'Richards Bay'),
('RBV', 'Ramata'),
('RBB', 'Borba Airport'),
('RAH', 'Rafha Domestic'),
('RAB', 'Rabaul'),
('QUP', 'Saqqaq Heliport'),
('QSZ', 'Yeerqiang Airport'),
('QRY', 'Ikerassaarsuk Heliport'),
('QPW', 'Kangaatsiaq Heliport'),
('QMK', 'Niaqornaarsuk Heliport'),
('QLS', 'Lausanne-la Blecherette Airport'),
('QIG', 'Iguatu Airport'),
('QGP', 'Garanhuns Airport'),
('QBC', 'Bella Coola'),
('PZY', 'Piešťany'),
('PZI', 'Panzhihua Bao anying'),
('PZB', 'Pietermaritzburg'),
('PYT', 'Paracatu Airport'),
('PTQ', 'Porto de Moz Airport'),
('PSU', 'Pangsuma'),
('PSG', 'Petersburg James A. Johnson'),
('PSE', 'Mercedita'),
('PRM', 'Portimão'),
('PRC', 'Ernest A. Love Field'),
('PQI', 'Northern Maine Regional Airport at Presque Isle'),
('PPW', 'Papa Westray'),
('POW', 'Portoroz Airport'),
('POL', 'Pemba'),
('POG', 'Port-Gentil International'),
('PNR', 'Pointe Noire'),
('PNP', 'Girua'),
('PNI', 'Pohnpei International'),
('PND', 'Punta Gorda'),
('PMZ', 'Palmar Sur'),
('PMF', 'Parma'),
('PLO', 'Port Lincoln'),
('PLN', 'Pellston Regional'),
('PKE', 'Parkes'),
('PKC', 'Petropavlovsk-Kamchatsky'),
('PJA', 'Pajala'),
('PIS', 'Poitiers–Biard'),
('PIK', 'Glasgow Prestwick'),
('PIH', 'Pocatello Regional'),
('PIB', 'Hattiesburg–Laurel Regional'),
('PHF', 'Newport News/Williamsburg International'),
('PGV', 'Pitt–Greenville'),
('PEZ', 'Penza'),
('PEU', 'Puerto Lempira'),
('PEE', 'Perm International'),
('PED', 'Pardubice Airport'),
('PEC', 'Pelican Sea Plane Base'),
('PCN', 'Picton Aerodrome'),
('PBZ', 'Plettenberg Bay'),
('PBU', 'Putao'),
('PBJ', 'Paama'),
('PAV', 'Paulo Afonso'),
('PAF', 'Pakuba Airfield'),
('OZZ', 'Ouarzazate'),
('OZG', 'Zagora'),
('OYE', 'Oyem'),
('OVB', 'Tolmachevo'),
('OUZ', 'Tazadit'),
('OTZ', 'Ralph Wien Memorial'),
('OTI', 'Leo Wattimena'),
('OTH', 'Southwest Oregon Regional'),
('OSY', 'Namsos Airport, Høknesøra'),
('OSD', 'Åre Östersund'),
('ORX', 'Oriximiná Airport'),
('ORH', 'Worcester Regional'),
('ORB', 'Örebro'),
('OPP', 'Salinópolis Airport'),
('ONJ', 'Odate–Noshiro'),
('ONG', 'Mornington Island'),
('OND', 'Ondangwa Airport'),
('OMS', 'Omsk Tsentralny'),
('OME', 'Nome'),
('OMD', 'Oranjemund'),
('OLP', 'Olympic Dam'),
('OKU', 'Mokuti Lodge Airport'),
('OKR', 'Yorke Island Airport'),
('OKE', 'Okinoerabu'),
('OIR', 'Okushiri'),
('OHS', 'Sohar'),
('OHE', 'Mohe Gulian'),
('OGZ', 'Beslan'),
('OGX', 'Ain Beida'),
('OGN', 'Yonaguni'),
('ODY', 'Oudomsay'),
('ODN', 'Long Seridan'),
('ODB', 'Cordoba Airport'),
('OCJ', 'Boscobel Aerodrome'),
('OCC', 'Francisco de Orellana'),
('OBY', 'Ittoqqortoormiit Heliport'),
('OBO', 'Tokachi–Obihiro'),
('OAL', 'Cacoal'),
('OAG', 'Orange'),
('NZL', '扎兰屯机场'),
('NZH', 'Manzhouli Xijiao'),
('NYT', 'Naypyidaw'),
('NYK', 'Nanyuki'),
('NVI', 'Navoi International'),
('NUX', 'Novy Urengoy'),
('NUS', 'Norsup'),
('NUF', 'Hatton Castlereigh Resrvr SPB'),
('NTX', 'Ranai'),
('NTQ', 'Noto'),
('NTN', 'Normanton'),
('NSR', 'São Raimundo Nonato Airport'),
('NSQ', 'Nuussuaq Heliport'),
('NSK', 'Alykel'),
('NRL', 'North Ronaldsay'),
('NRK', 'Norrköping'),
('NRA', 'Narrandera'),
('NPY', 'Mpanda Airport'),
('NPL', 'New Plymouth'),
('NPE', 'Hawke''s Bay'),
('NOV', 'Albano Machado'),
('NNB', 'Santa Ana'),
('NMF', 'Maafaru International Airport'),
('NLT', 'Xinyuan Nalati'),
('NLK', 'Norfolk Island'),
('NLH', 'Ninglang Luguhu'),
('NLF', 'Darnley Island Airport'),
('NJC', 'Nizhnevartovsk'),
('NIU', 'Niau'),
('NIS', 'Simberi Airport'),
('NHV', 'Nuku Hiva'),
('NGQ', 'Ngari Gunsa'),
('NGE', 'Ngaoundéré'),
('NEU', 'Nathong'),
('NDY', 'Sanday'),
('NDG', 'Qiqihar Sanjiazi'),
('NBX', 'Nabire'),
('NBS', 'Changbaishan'),
('NAU', 'Napuka'),
('NAQ', 'Qaanaaq'),
('NAO', 'Nanchong Gaoping'),
('NAM', 'Namlea Airport'),
('NAJ', 'Nakhchivan International'),
('NAH', 'Naha'),
('NAA', 'Narrabri'),
('MZW', 'Mecheria Airport'),
('MZH', 'Amasya Merzifon'),
('MZA', 'Mayor Pnp Nancy Flore Airport'),
('MYW', 'Mtwara'),
('MYI', 'Murray Island'),
('MYG', 'Mayaguana'),
('MYA', 'Moruya'),
('MXZ', 'Meixian'),
('MXX', 'Mora–Siljan'),
('MXV', 'Mörön'),
('MXH', 'Moro'),
('MWX', 'Muan International'),
('MWF', 'Maewo-Naone'),
('MVT', 'Mataiva'),
('MVR', 'Salak'),
('MVP', 'Fabio Alberto León Bentley'),
('MVB', 'M Vengue El Hadj Omar Bongo Ondimba International'),
('MUR', 'Marudi'),
('MUK', 'Mauke Airport'),
('MUA', 'Munda'),
('MTV', 'Mota Lava'),
('MTE', 'Monte Alegre Airport'),
('MSR', 'Muş'),
('MSQ', 'Minsk National'),
('MSH', 'Masirah Air Base'),
('MSA', 'Muskrat Dam'),
('MRZ', 'Moree'),
('MRV', 'Mineralnye Vody'),
('MQX', 'Alula Aba Nega'),
('MQT', 'Sawyer International'),
('MQL', 'Mildura'),
('MPA', 'Katima Mulilo'),
('MOV', 'Moranbah'),
('MOI', 'Mitiaro Island Airport'),
('MOH', 'Maleo Airport'),
('MNX', 'Manicoré Airport'),
('MNU', 'Mawlamyine'),
('MNS', 'Mansa Airport'),
('MNG', 'Maningrida'),
('MNC', 'Nacala'),
('MNA', 'Melangguane'),
('MMK', 'Murmansk'),
('MMD', 'Minami-Daito'),
('MLU', 'Monroe Regional'),
('MKQ', 'Mopah International'),
('MKP', 'Makemo'),
('MJU', 'Tampa Padang'),
('MJM', 'Mbuji Mayi'),
('MJK', 'Shark Bay'),
('MJF', 'Mosjøen Airport, Kjærstad'),
('MJC', 'Man'),
('MIS', 'Misima Island'),
('MII', 'Marília'),
('MHX', 'Manihiki Island Airport'),
('MHG', 'Mannheim City'),
('MGZ', 'Myeik'),
('MGT', 'Milingimbi'),
('MGS', 'Mangaia Island Airport'),
('MGM', 'Montgomery Regional'),
('MGH', 'Margate'),
('MFK', 'Matsu Beigan'),
('MEU', 'Monte Dourado Airport'),
('MEQ', 'Cut Nyak Dhien'),
('MEH', 'Mehamn'),
('MEE', 'Mare Airport'),
('MDK', 'Mbandaka'),
('MDI', 'Makurdi Airport'),
('MDG', 'Mudanjiang Hailang International'),
('MCX', 'Uytash'),
('MCW', 'Mason City Municipal'),
('MCV', 'McArthur River Mine'),
('MBQ', 'Mbarara Airport'),
('MAU', 'Maupiti'),
('MAS', 'Momote'),
('MAJ', 'Marshall Islands International'),
('MAG', 'Madang'),
('LZY', 'Nyingchi Mainling'),
('LZO', 'Luzhou Yunlong'),
('LZH', 'Liuzhou Bailian'),
('LYI', 'Linyi Shubuling'),
('LYH', 'Lynchburg Regional'),
('LYG', 'Lianyungang Baitabu'),
('LYC', 'Lycksele'),
('LYA', 'Luoyang Beijiao'),
('LWY', 'Lawas'),
('LWS', 'Lewiston–Nez Perce County'),
('LWE', 'Wonopito'),
('LUV', 'Karel Sadsuitubun Airport'),
('LUQ', 'Brigadier Mayor César Raúl Ojeda'),
('LUP', 'Kalaupapa Airport'),
('LUO', 'Luena'),
('LUM', 'Dehong Mangshi'),
('LUD', 'Lüderitz'),
('LTI', 'Altai'),
('LSW', 'Malikus Saleh'),
('LSS', 'Terre-de-Haut Airport'),
('LSH', 'Lashio'),
('LSE', 'La Crosse Regional'),
('LRU', 'Las Cruces International Airport'),
('LRT', 'Lorient South Brittany'),
('LRR', 'Larestan International'),
('LRE', 'Longreach'),
('LQM', 'Caucayá'),
('LPY', 'Le Puy – Loudes'),
('LPP', 'Lappeenranta'),
('LPM', 'Malekoula'),
('LPF', 'Liupanshui Yuezhao'),
('LPD', 'La Pedrera'),
('LOO', 'L Mekrareg'),
('LOD', 'Longana'),
('LNV', 'Lihir Island'),
('LNU', 'Robert Atty Bessing Airport'),
('LNL', 'Longnan Chengzhou Airport'),
('LNJ', 'Lincang'),
('LNE', 'Lonorore'),
('LNB', 'Lamen Bay'),
('LMV', 'Madivaru Airport'),
('LLV', 'Lüliang'),
('LLU', 'Alluitsup Paa Heliport'),
('LLI', 'Lalibela'),
('LKL', 'Lakselv Airport, Banak'),
('LKH', 'Long Akah'),
('LKB', 'Lakeba'),
('LKA', 'Gewayantana'),
('LIF', 'Ouanaham'),
('LHN', 'Linhares Municipal Airport'),
('LGL', 'Long Lellang'),
('LED', 'Pulkovo International'),
('LDS', 'Yichun Lindu'),
('LDH', 'Lord Howe Island'),
('LCX', 'Longyan Guanzhishan'),
('LCR', 'La Chorrera'),
('LCJ', 'Łódź Władysław Reymont'),
('LCH', 'Lake Charles Regional'),
('LBS', 'Labasa'),
('LBR', 'Lábrea Airport'),
('LBP', 'Long Banga'),
('LBL', 'Liberal Mid-America Regional'),
('LBF', 'North Platte Regional'),
('LBD', 'Khujand'),
('LAW', 'Lawton–Fort Sill Regional'),
('LAR', 'Laramie Regional'),
('LAH', 'Oesman Sadik'),
('LAF', 'Purdue University Airport'),
('KZS', 'Kastellorizo'),
('KZR', 'Zafer'),
('KZN', 'Kazan International'),
('KZI', 'Kozani National'),
('KYP', 'Kyaukpyu'),
('KXU', 'Katiu'),
('KXF', 'Koro Island Airport'),
('KWM', 'Kowanyama'),
('KWA', 'Bucholz Army Airfield'),
('KVG', 'Kavieng'),
('KUZ', 'Kuummiut Heliport'),
('KUS', 'Kulusuk'),
('KUG', 'Kubin Island'),
('KUF', 'Kurumoch International'),
('KTR', 'RAAF Base Tindal'),
('KTL', 'Kitale'),
('KTJ', 'Kichwa Tembo Airstrip'),
('KTD', 'Kitadaito'),
('KTA', 'Karratha'),
('KSU', 'Kristiansund Airport, Kvernberget'),
('KSQ', 'Karshi'),
('KSO', 'Kastoria National'),
('KSM', 'St. Mary s'),
('KSJ', 'Kasos Island Public'),
('KSA', 'Kosrae International'),
('KRY', 'Karamay'),
('KRT', 'Khartoum International'),
('KRL', 'Korla'),
('KRF', 'Höga Kusten'),
('KRB', 'Karumba'),
('KQH', 'Kishangarh Airport'),
('KPO', 'Pohang'),
('KOV', 'Kokshetau'),
('KOK', 'Kokkola-Pietarsaari'),
('KNS', 'King Island'),
('KNQ', 'Kone Airport'),
('KNH', 'Kinmen'),
('KNG', 'Kaimana'),
('KND', 'Kindu'),
('KMV', 'Kalaymyo'),
('KMK', 'Makabana Airport'),
('KLW', 'Klawock'),
('KLU', 'Klagenfurt'),
('KLR', 'Kalmar'),
('KKR', 'Kaukura'),
('KKE', 'Kerikeri'),
('KJI', 'Kanas'),
('KJA', 'Yemelyanovo International'),
('KIR', 'Kerry'),
('KIF', 'Kingfisher Lake'),
('KIE', 'Aropa'),
('KID', 'Kristianstad'),
('KHZ', 'Kauehi'),
('KHX', 'Kihihi Airstrip'),
('KHV', 'Khabarovsk Novy'),
('KHQ', 'Kullorsuaq Heliport'),
('KGT', 'Kangding'),
('KGQ', 'Kangersuatsiaq Heliport'),
('KGE', 'Kaghau'),
('KGD', 'Khrabrovo'),
('KGA', 'Kananga'),
('KFS', 'Kastamonu'),
('KEW', 'Keewaywin'),
('KET', 'Kengtung'),
('KEO', 'Odienne'),
('KEM', 'Kemi-Tornio'),
('KDW', 'Victoria Reservoir SPB'),
('KDO', 'Kadhdhoo'),
('KDM', 'Kaadedhdhoo'),
('KCT', 'Koggala'),
('KCM', 'Kahramanmaraş'),
('KCA', 'Kuqa Qiuci'),
('KBU', 'Gusti Syamsir Alam'),
('KBH', 'Kahama Buzwagi'),
('KAW', 'Kawthaung'),
('KAE', 'Kake Sea Plane Base'),
('KAA', 'Kasama'),
('JYV', 'Jyvaskyla'),
('JXA', 'Jixi Xingkaihu'),
('JUV', 'Upernavik'),
('JUH', 'Chizhou Jiuhuashan'),
('JTY', 'Astypalaia Island National'),
('JSU', 'Maniitsoq'),
('JST', 'Johnstown–Cambria County'),
('JSO', 'Sobral Airport'),
('JSJ', 'Jiansanjiang'),
('JSB', 'São Benedito Airport'),
('JRT', 'Juruti Airport'),
('JRH', 'Jorhat'),
('JQA', 'Qaarsut'),
('JPO', 'Patos Airport'),
('JOG', 'Adisutjipto International'),
('JNZ', 'Jinzhou Xiaolingzi'),
('JNS', 'Narsaq Heliport'),
('JNN', 'Nanortalik Heliport'),
('JMU', 'Jiamusi Dongjiao'),
('JMS', 'Jamestown Regional'),
('JMJ', 'Lancang Jingmai Airport'),
('JMA', 'Manhuacu Elias Breder Airport'),
('JJU', 'Qaqortoq Heliport'),
('JJM', 'Meru-Kinna Mulika Lodge'),
('JJG', 'Jaguaruna Regional'),
('JIU', 'Jiujiang Lushan Airport'),
('JIQ', 'Qianjiang Wulingshan'),
('JIM', 'Aba Segud'),
('JIC', 'Jinchang Jinchuan'),
('JIA', 'Juína Airport'),
('JHS', 'Sisimiut'),
('JGS', 'Jinggangshan'),
('JGO', 'Qeqertarsuaq Heliport'),
('JGN', 'Jiayuguan'),
('JGD', 'Jiagedaqi'),
('JFR', 'Paamiut'),
('JEK', 'Lower Zambezi Nat.Park Jeki'),
('JEG', 'Aasiaat'),
('JEE', 'Jeremie Airport'),
('JDZ', 'Jingdezhen Luojia'),
('JCS', 'Crateús Airport'),
('JCK', 'Julia Creek'),
('JCH', 'Qasigiannguit Heliport'),
('JAW', 'Araripina Airport'),
('JAE', 'Jaén'),
('IWJ', 'Iwami'),
('IVR', 'Inverell'),
('IUE', 'Niue International'),
('ITB', 'Itaituba'),
('ISK', 'Gandhinagar Airport'),
('ISE', 'Isparta Süleyman Demirel'),
('IRZ', 'Tapuruquara Airport'),
('IRG', 'Lockhart River'),
('IRA', 'Kirakira'),
('IQN', 'Qingyang'),
('IPA', 'Ipota'),
('IOQ', 'Isortoq Heliport'),
('INZ', 'In Salah'),
('INL', 'Falls International'),
('INH', 'Inhambane'),
('INF', 'In Guezzam Airport'),
('INC', 'Yinchuan Hedong International'),
('INB', 'Independence'),
('IMT', 'Ford'),
('ILQ', 'Ilo Airport'),
('ILP', 'Île des Pins'),
('ILD', 'Lleida–Alguaire'),
('IKT', 'International Airport Irkutsk'),
('IKI', 'Iki'),
('IGA', 'Inagua'),
('IFU', 'Ifuru'),
('IFJ', 'Ísafjörður'),
('ICI', 'Cicia'),
('IBB', 'General Villamil Airport'),
('IAM', 'In Amenas'),
('IAL', 'Salinas Airport'),
('HYS', 'Hays Regional'),
('HXD', 'Delingha Airport'),
('HVG', 'Honningsvåg Airport, Valan'),
('HUZ', 'Huizhou Pingtan'),
('HUY', 'Humberside'),
('HUN', 'Hualien'),
('HTT', 'Huatugou Airport'),
('HTN', 'Hotan'),
('HTA', 'Kadala'),
('HSN', 'Zhoushan Putuoshan'),
('HSG', 'Saga'),
('HRF', 'Hoarafushi Airport'),
('HOM', 'Homer'),
('HOI', 'Hao'),
('HOB', 'Lea County Regional'),
('HNY', 'Hengyang Nanyue'),
('HNS', 'Haines'),
('HNH', 'Hoonah'),
('HNA', 'Hanamaki'),
('HMI', 'Hami'),
('HME', 'Oued Irara–Krim Belkacem'),
('HLH', 'Ulanhot'),
('HLE', 'Saint Helena'),
('HLD', 'Hulunbuir Hailar'),
('HKN', 'Hoskins'),
('HKK', 'Hokitika'),
('HJJ', 'Huaihua Zhijiang'),
('HIS', 'Hayman Island Heliport'),
('HID', 'Horn Island'),
('HIB', 'Range Regional'),
('HIA', 'Huai an Lianshui'),
('HHZ', 'Hikueru'),
('HHR', 'Hawthorne Municipal'),
('HHH', 'Hilton Head'),
('HGO', 'Korhogo'),
('HGN', 'Mae Hong Son'),
('HGD', 'Hughenden'),
('HFS', 'Hagfors'),
('HEK', 'Heihe'),
('HEH', 'Heho'),
('HDK', 'Kulhudhuffushi Airport'),
('HDG', 'Handan'),
('HDF', 'Heringsdorf'),
('HCJ', 'Hechi Jinchengjiang'),
('HBY', 'Homa Bay Airport'),
('HBQ', 'Haibei Qilian Airport'),
('HAQ', 'Hanimaadhoo International'),
('HAD', 'Halmstad'),
('HAC', 'Hachijojima'),
('HAA', 'Hasvik'),
('GZG', 'Garze Gesar Airport'),
('GYU', 'Guyuan Liupanshan'),
('GYA', 'Guayaramerín'),
('GXH', 'Gannan Xiahe'),
('GUR', 'Gurney'),
('GTR', 'Golden Triangle Regional'),
('GTE', 'Groote Eylandt'),
('GST', 'Gustavus'),
('GRV', 'Grozny'),
('GPB', 'Tancredo Thomaz de Faria'),
('GOQ', 'Golmud'),
('GOJ', 'Strigino International'),
('GOB', 'Robe Airport'),
('GMZ', 'La Gomera'),
('GMR', 'Totegegie'),
('GMQ', 'Golog Maqin'),
('GMO', 'Gombe Lawanti International'),
('GMB', 'Gambela'),
('GLT', 'Gladstone'),
('GLN', 'Guelmim'),
('GKK', 'Kooddoo'),
('GKA', 'Goroka'),
('GJL', 'Jijel Ferhat Abbas'),
('GIC', 'Boigu Island Airport'),
('GHC', 'Great Harbour Cay Airport'),
('GGW', 'Glasgow'),
('GGF', 'Grant Municipal Airport'),
('GFF', 'Griffith'),
('GEV', 'Gällivare'),
('GEA', 'Nouméa Magenta'),
('GDE', 'Gode'),
('GCK', 'Garden City Regional'),
('GCC', 'Gillette–Campbell County'),
('GBJ', 'Les Bases Airport'),
('GBI', 'Kalaburagi Airport'),
('FYN', 'Fuyun Koktokay'),
('FYJ', 'Fuyuan Dongji'),
('FVM', 'Fuvahmulah'),
('FUJ', 'Fukue'),
('FUG', 'Fuyang Xiguan'),
('FTU', 'Tôlanaro'),
('FTA', 'Futuna'),
('FSZ', 'Shizuoka'),
('FRL', 'Forli Airport'),
('FRE', 'Fera'),
('FOD', 'Fort Dodge Regional'),
('FNI', 'Nîmes–Alès–Camargue–Cévennes'),
('FND', 'Funadhoo Airport'),
('FMI', 'Kalemie'),
('FLZ', 'Ferdinand Lumban Tobing'),
('FLO', 'Florence Regional'),
('FKS', 'Fukushima'),
('FKQ', 'Fakfak Torea'),
('FKI', 'Bangoka International'),
('FJR', 'Fujairah International Airport'),
('FDE', 'Førde Airport, Bringeland'),
('FAV', 'Fakarava'),
('FAC', 'Faaite'),
('EWB', 'New Bedford Regional'),
('EVG', 'Sveg'),
('EUX', 'F. D. Roosevelt'),
('EUQ', 'Evelio Javier Airport'),
('ESC', 'Delta County'),
('ERN', 'Eirunepé Airport'),
('ERI', 'Erie International'),
('EPR', 'Esperance'),
('EOI', 'Eday'),
('ENY', 'Yan an Ershilipu'),
('ENH', 'Enshi Xujiaping'),
('EMN', 'Nema Airport'),
('EMD', 'Emerald'),
('ELV', 'Elfin Cove Seaplane Base'),
('ELG', 'El Golea'),
('ELC', 'Elcho Island'),
('EKO', 'Elko Regional'),
('EGM', 'Seghe'),
('EGC', 'Bergerac Dordogne Périgord'),
('EDR', 'Edward River'),
('EBJ', 'Esbjerg'),
('EBH', 'El Bayadh'),
('EBG', 'El Bagre'),
('EBA', 'Marina di Campo'),
('DWO', 'Kotte Diyawanna Oya SPB'),
('DVL', 'Devils Lake Regional'),
('DUT', 'Unalaska'),
('DSN', 'Ordos Ejin Horo'),
('DSE', 'Combolcha'),
('DQA', 'Daqing Sartu'),
('DOL', 'Deauville – Normandie'),
('DOB', 'Dobo'),
('DNH', 'Dunhuang'),
('DME', 'Domodedovo International'),
('DMD', 'Doomadgee'),
('DMB', 'Taraz'),
('DLZ', 'Dalanzadgad'),
('DLY', 'Dillon''s Bay'),
('DLU', 'Dali'),
('DLE', 'Dole–Jura'),
('DKR', 'Léopold Sédar Senghor International'),
('DIU', 'Diu'),
('DIK', 'Dickinson Theodore Roosevelt Regional'),
('DIE', 'Arrachart'),
('DGE', 'Mudgee'),
('DEM', 'Dembi Dolo'),
('DEC', 'Decatur'),
('DDG', 'Dandong Langtou'),
('DDC', 'Dodge City Regional'),
('DCY', 'Daocheng Yading'),
('DCM', 'Castres–Mazamet'),
('DCF', 'Canefield'),
('DAU', 'Daru'),
('DAT', 'Datong Yungang'),
('CZH', 'Corozal'),
('CYI', 'Chiayi'),
('CWJ', 'Cangyuan Washan'),
('CWA', 'Central Wisconsin'),
('CVU', 'Corvo'),
('CVQ', 'Carnarvon'),
('CUF', 'Cuneo International'),
('CTL', 'Charleville'),
('CTD', 'Chitre Alonso Valderrama'),
('CTC', 'Coronel Felipe Varela International'),
('CSU', 'Santa Cruz do Sul Airport'),
('CRI', 'Colonel Hill'),
('CPR', 'Casper–Natrona County International'),
('CPD', 'Coober Pedy'),
('COU', 'Columbia Regional'),
('CNP', 'Nerlerit Inaat'),
('CNJ', 'Cloncurry'),
('CNC', 'Coconut Island Airport'),
('CMX', 'Houghton County Memorial'),
('CMI', 'University of Illinois Willard'),
('CMF', 'Chambéry'),
('CMA', 'Cunnamulla'),
('CLV', 'Caldas Novas'),
('CJZ', 'Cajazeiras Airport'),
('CJL', 'Chitral'),
('CIZ', 'Municipal Airport Danilson Aires Cirino da Silva / Coari Airport'),
('CIU', 'Chippewa County International'),
('CIH', 'Changzhi Wangcun'),
('CIF', 'Chifeng Yulong'),
('CHY', 'Choiseul Bay'),
('CHT', 'Chatham Islands-Tuuta Airport'),
('CHG', 'Chaoyang'),
('CGD', 'Changde Taohuayuan'),
('CFK', 'Chlef International'),
('CED', 'Ceduna'),
('CDV', 'Merle K. (Mudhole) Smith'),
('CDE', 'Chengde Puning'),
('CDC', 'Cedar City Regional'),
('CDB', 'Cold Bay'),
('CCV', 'Craig Cove'),
('CCK', 'Cocos (Keeling) Islands'),
('CCF', 'Carcassonne'),
('CBT', 'Catumbela'),
('CAZ', 'Cobar'),
('CAW', 'Bartolomeu Lysandro'),
('CAU', 'Caruaru Airport'),
('CAT', 'Cascais Tires'),
('CAQ', 'Juan H. White'),
('CAL', 'Campbeltown'),
('CAH', 'Cà Mau'),
('BZX', 'Bazhong Enyang Airport'),
('BZR', 'Béziers Cap d Agde'),
('BYR', 'Laeso Airport'),
('BYK', 'Bouaké'),
('BXG', 'Bendigo Airport'),
('BWT', 'Burnie'),
('BVS', 'Breves Airport'),
('BVI', 'Birdsville'),
('BVH', 'Vilhena'),
('BVG', 'Berlevåg'),
('BUW', 'Baubau'),
('BUT', 'Bathpalathang'),
('BUN', 'Gerardo Tobar López'),
('BUC', 'Burketown'),
('BUA', 'Buka'),
('BTW', 'Batu Licin'),
('BTM', 'Bert Mooney'),
('BSG', 'Bata'),
('BSD', 'Baoshan Yunrui'),
('BRR', 'Barra'),
('BRQ', 'Brno–Tuřany'),
('BRD', 'Brainerd Lakes Regional'),
('BQS', 'Ignatyevo'),
('BQL', 'Boulia'),
('BQK', 'Brunswick Golden Isles'),
('BPX', 'Qamdo Bamda'),
('BPT', 'Jack Brooks Regional'),
('BPL', 'Bole Alashankou'),
('BPG', 'Barra do Garças'),
('BPE', 'Qinhuangdao Beidaihe'),
('BNY', 'Bellona/Anua'),
('BNN', 'Brønnøysund Airport, Brønnøy'),
('BMW', 'Bordj Mokhtar'),
('BMO', 'Bhamo'),
('BLJ', 'Mostépha Ben Boulaid'),
('BKZ', 'Bukoba'),
('BKS', 'Fatmawati Soekarno'),
('BKQ', 'Blackall'),
('BKM', 'Ba kelalan'),
('BJZ', 'Badajoz'),
('BJR', 'Bahir Dar'),
('BJI', 'Bemidji Regional'),
('BJF', 'Båtsfjord'),
('BIH', 'Eastern Sierra Regional Airport'),
('BHY', 'Beihai Fucheng'),
('BHQ', 'Broken Hill'),
('BGX', 'Comandante Gustavo Kraemer Airport'),
('BGM', 'Greater Binghamton'),
('BGG', 'Bingöl'),
('BGC', 'Braganca'),
('BFX', 'Bafoussam'),
('BFJ', 'Bijie Feixiong'),
('BFF', 'Western Nebraska Regional'),
('BEU', 'Bedourie'),
('BET', 'Bethel'),
('BEM', 'Beni Mellal'),
('BDD', 'Badu Island Airport'),
('BCO', 'Baco'),
('BCI', 'Barcaldine'),
('BBN', 'Bario'),
('BAV', 'Baotou'),
('BAS', 'Balalae'),
('BAR', 'Qionghai Bo''ao'),
('AZR', 'Touat-Cheikh Sidi Mohamed Belkebir'),
('AZO', 'Kalamazoo/Battle Creek International'),
('AXR', 'Arutua'),
('AXP', 'Spring Point'),
('AWD', 'Aniwa'),
('AUY', 'Anatom'),
('AUX', 'Araguaína'),
('AUU', 'Aurukun'),
('AUR', 'Aurillac – Tronquières'),
('ATD', 'Uru Harbour'),
('ATA', 'Comandante FAP Germán Arias Graziani'),
('ASO', 'Asosa'),
('ASF', 'Narimanovo'),
('ARW', 'Arad International'),
('AQG', 'Anqing Tianzhushan'),
('APN', 'Alpena County Regional'),
('APK', 'Apataki'),
('AOG', 'Anshan Teng ao'),
('AMH', 'Arba Minch'),
('ALQ', 'Alegrete Airport'),
('ALO', 'Waterloo Regional'),
('AKY', 'Sittwe'),
('AKV', 'Akulivik'),
('AKU', 'Aksu'),
('AKS', 'Auki Gwaunaru u'),
('AKA', 'Ankang Airport'),
('AJN', 'Ouani'),
('AIU', 'Enua'),
('AIR', 'Aripuanã Airport'),
('AHX', 'Anholt Airport'),
('AHU', 'Cherif Al Idrissi'),
('AHJ', 'Aba/Hongyuan'),
('AHE', 'Ahe'),
('AGN', 'Angoon Seaplane Base'),
('AGM', 'Tasiilaq Ammassalik Heliport'),
('AGH', 'Ängelholm–Helsingborg'),
('AEX', 'Alexandria International'),
('AER', 'Sochi International'),
('AEI', 'Algeciras Heliport'),
('AEB', 'Baise Bama'),
('ADK', 'Adak'),
('ACX', 'Xingyi Wanfenglin'),
('ACH', 'St. Gallen–Altenrhein'),
('ABY', 'Southwest Georgia Regional'),
('ABU', 'Haliwen'),
('ABR', 'Aberdeen Regional'),
('ABM', 'Northern Peninsula'),
('ABI', 'Abilene Regional'),
('ABC', 'Albacete-Los Llanos Airport'),
('AAT', 'Altay'),
('AAM', 'Malamala Airport'),
('AAA', 'Anaa');